// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>


@interface AIBinaryResult : NSObject

- (void)onResult:(nonnull NSData *)data;

@end
