// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIBlock+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Block::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.rowBeg),
            ::djinni::I32::toCpp(obj.rowEnd),
            ::djinni::I32::toCpp(obj.colBeg),
            ::djinni::I32::toCpp(obj.colEnd)};
}

auto Block::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIBlock alloc] initWithRowBeg:(::djinni::I32::fromCpp(cpp.row_beg))
                                    rowEnd:(::djinni::I32::fromCpp(cpp.row_end))
                                    colBeg:(::djinni::I32::fromCpp(cpp.col_beg))
                                    colEnd:(::djinni::I32::fromCpp(cpp.col_end))];
}

}  // namespace djinni_generated
