// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import <Foundation/Foundation.h>

@interface AIBlock : NSObject
- (nonnull instancetype)initWithRowBeg:(int32_t)rowBeg
                                rowEnd:(int32_t)rowEnd
                                colBeg:(int32_t)colBeg
                                colEnd:(int32_t)colEnd;
+ (nonnull instancetype)blockWithRowBeg:(int32_t)rowBeg
                                 rowEnd:(int32_t)rowEnd
                                 colBeg:(int32_t)colBeg
                                 colEnd:(int32_t)colEnd;

@property (nonatomic, readonly) int32_t rowBeg;

@property (nonatomic, readonly) int32_t rowEnd;

@property (nonatomic, readonly) int32_t colBeg;

@property (nonatomic, readonly) int32_t colEnd;

@end
