// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIBlock.h"
#include "block.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIBlock;

namespace djinni_generated {

struct Block
{
    using CppType = ::ai::Block;
    using ObjcType = AIBlock*;

    using Boxed = Block;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
