// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIBlock.h"


@implementation AIBlock

- (nonnull instancetype)initWithRowBeg:(int32_t)rowBeg
                                rowEnd:(int32_t)rowEnd
                                colBeg:(int32_t)colBeg
                                colEnd:(int32_t)colEnd
{
    if (self = [super init]) {
        _rowBeg = rowBeg;
        _rowEnd = rowEnd;
        _colBeg = colBeg;
        _colEnd = colEnd;
    }
    return self;
}

+ (nonnull instancetype)blockWithRowBeg:(int32_t)rowBeg
                                 rowEnd:(int32_t)rowEnd
                                 colBeg:(int32_t)colBeg
                                 colEnd:(int32_t)colEnd
{
    return [[self alloc] initWithRowBeg:rowBeg
                                 rowEnd:rowEnd
                                 colBeg:colBeg
                                 colEnd:colEnd];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p rowBeg:%@ rowEnd:%@ colBeg:%@ colEnd:%@>", self.class, (void *)self, @(self.rowBeg), @(self.rowEnd), @(self.colBeg), @(self.colEnd)];
}

@end
