// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>


@interface AIBoolResult : NSObject

- (void)onResult:(BOOL)success;

@end
