// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIBoolResult+Private.h"
#import "AIBoolResult.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface AIBoolResult ()

- (id)initWithCpp:(const std::shared_ptr<::ai::BoolResult>&)cppRef;

@end

@implementation AIBoolResult {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ai::BoolResult>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ai::BoolResult>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onResult:(BOOL)success {
    try {
        _cppRefHandle.get()->on_result(::djinni::Bool::toCpp(success));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto BoolResult::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto BoolResult::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<AIBoolResult>(cpp);
}

}  // namespace djinni_generated

@end
