// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "bool_result.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIBoolResult;

namespace djinni_generated {

class BoolResult
{
public:
    using CppType = std::shared_ptr<::ai::BoolResult>;
    using CppOptType = std::shared_ptr<::ai::BoolResult>;
    using ObjcType = AIBoolResult*;

    using Boxed = BoolResult;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

