// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AICancellationToken+Private.h"
#import "AICancellationToken.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class CancellationToken::ObjcProxy final
: public ::ai::CancellationToken
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::CancellationToken;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void cancel() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() cancel];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto CancellationToken::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto CancellationToken::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
