// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, AIColour)
{
    AIColourWhite,
    AIColourLightBlue,
    AIColourDirtyBlue,
    AIColourDarkGrey,
    AIColourLightGrey,
    AIColourPurple,
    AIColourRed,
    AIColourNone,
};
