// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, AIDataType)
{
    AIDataTypeText,
    AIDataTypeMultilineText,
    AIDataTypeBoolean,
    AIDataTypeEmail,
    AIDataTypePassword,
    AIDataTypeReference,
    AIDataTypeChoice,
    AIDataTypeSkype,
    AIDataTypePhone,
    AIDataTypeCurrency,
    AIDataTypeUrl,
    AIDataTypeInteger,
    AIDataTypeRating,
};
