// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIDirectoriesDetail.h"
#import "AIFileState.h"
#import "AIFilesDetail.h"
#import <Foundation/Foundation.h>


@protocol AIDirectoryView

- (void)refreshList:(nonnull NSArray<NSNumber *> *)folderPath
               dirs:(nonnull AIDirectoriesDetail *)dirs
              files:(nonnull AIFilesDetail *)files
  newDirectoryNames:(nonnull NSArray<NSString *> *)newDirectoryNames
       newFileNames:(nonnull NSArray<NSString *> *)newFileNames;

- (void)fileStatesChanged:(nonnull NSArray<NSNumber *> *)folderPath
                  fileIds:(nonnull NSArray<NSNumber *> *)fileIds
                   states:(nonnull NSArray<NSNumber *> *)states;

- (void)fileChanged:(nonnull NSArray<NSNumber *> *)folderPath
             fileId:(int32_t)fileId
         fileNameId:(int32_t)fileNameId
               size:(int64_t)size
         percentage:(int32_t)percentage
              state:(AIFileState)state
          thumbnail:(nonnull NSData *)thumbnail;

@end
