// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIDirectoriesDetail.h"
#include "directories_detail.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIDirectoriesDetail;

namespace djinni_generated {

struct DirectoriesDetail
{
    using CppType = ::ai::DirectoriesDetail;
    using ObjcType = AIDirectoriesDetail*;

    using Boxed = DirectoriesDetail;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
