// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>

@interface AIDirectoriesDetail : NSObject
- (nonnull instancetype)initWithIds:(nonnull NSArray<NSNumber *> *)ids
                             titles:(nonnull NSArray<NSNumber *> *)titles;
+ (nonnull instancetype)directoriesDetailWithIds:(nonnull NSArray<NSNumber *> *)ids
                                          titles:(nonnull NSArray<NSNumber *> *)titles;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * ids;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * titles;

@end
