// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "directory_view.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol AIDirectoryView;

namespace djinni_generated {

class DirectoryView
{
public:
    using CppType = std::shared_ptr<::ai::DirectoryView>;
    using CppOptType = std::shared_ptr<::ai::DirectoryView>;
    using ObjcType = id<AIDirectoryView>;

    using Boxed = DirectoryView;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

