// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "diagnostic.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol AIDiagnostic;

namespace djinni_generated {

class Diagnostic
{
public:
    using CppType = std::shared_ptr<::ai::Diagnostic>;
    using CppOptType = std::shared_ptr<::ai::Diagnostic>;
    using ObjcType = id<AIDiagnostic>;

    using Boxed = Diagnostic;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

