// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#import "AIElement.h"
#include "element.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIElement;

namespace djinni_generated {

struct Element
{
    using CppType = ::ai::Element;
    using ObjcType = AIElement*;

    using Boxed = Element;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
