// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#import "AIElement+Private.h"
#import "AIElementType+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Element::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.group),
            ::djinni::Enum<::ai::ElementType, AIElementType>::toCpp(obj.type),
            ::djinni::I32::toCpp(obj.inputId),
            ::djinni::String::toCpp(obj.title),
            ::djinni::String::toCpp(obj.value)};
}

auto Element::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIElement alloc] initWithGroup:(::djinni::I32::fromCpp(cpp.group))
                                       type:(::djinni::Enum<::ai::ElementType, AIElementType>::fromCpp(cpp.type))
                                    inputId:(::djinni::I32::fromCpp(cpp.input_id))
                                      title:(::djinni::String::fromCpp(cpp.title))
                                      value:(::djinni::String::fromCpp(cpp.value))];
}

}  // namespace djinni_generated
