// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, AIElementType)
{
    AIElementTypeButton,
    AIElementTypeTextInput,
    AIElementTypeBoolInput,
    AIElementTypeEmailInput,
    AIElementTypeLabel,
    AIElementTypePasswordInput,
    AIElementTypeText,
};
