// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#import "AIElement.h"


@implementation AIElement

- (nonnull instancetype)initWithGroup:(int32_t)group
                                 type:(AIElementType)type
                              inputId:(int32_t)inputId
                                title:(nonnull NSString *)title
                                value:(nonnull NSString *)value
{
    if (self = [super init]) {
        _group = group;
        _type = type;
        _inputId = inputId;
        _title = [title copy];
        _value = [value copy];
    }
    return self;
}

+ (nonnull instancetype)elementWithGroup:(int32_t)group
                                    type:(AIElementType)type
                                 inputId:(int32_t)inputId
                                   title:(nonnull NSString *)title
                                   value:(nonnull NSString *)value
{
    return [[self alloc] initWithGroup:group
                                  type:type
                               inputId:inputId
                                 title:title
                                 value:value];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p group:%@ type:%@ inputId:%@ title:%@ value:%@>", self.class, (void *)self, @(self.group), @(self.type), @(self.inputId), self.title, self.value];
}

@end
