// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFileItemDetail.h"
#include "file_item_detail.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIFileItemDetail;

namespace djinni_generated {

struct FileItemDetail
{
    using CppType = ::ai::FileItemDetail;
    using ObjcType = AIFileItemDetail*;

    using Boxed = FileItemDetail;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
