// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFileItemDetail+Private.h"
#import "AIFileState+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto FileItemDetail::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.itemId),
            ::djinni::Enum<::ai::FileState, AIFileState>::toCpp(obj.state),
            ::djinni::Bool::toCpp(obj.selected),
            ::djinni::String::toCpp(obj.title),
            ::djinni::String::toCpp(obj.detail)};
}

auto FileItemDetail::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIFileItemDetail alloc] initWithItemId:(::djinni::I32::fromCpp(cpp.item_id))
                                              state:(::djinni::Enum<::ai::FileState, AIFileState>::fromCpp(cpp.state))
                                           selected:(::djinni::Bool::fromCpp(cpp.selected))
                                              title:(::djinni::String::fromCpp(cpp.title))
                                             detail:(::djinni::String::fromCpp(cpp.detail))];
}

}  // namespace djinni_generated
