// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFileState.h"
#import <Foundation/Foundation.h>

@interface AIFileItemDetail : NSObject
- (nonnull instancetype)initWithItemId:(int32_t)itemId
                                 state:(AIFileState)state
                              selected:(BOOL)selected
                                 title:(nonnull NSString *)title
                                detail:(nonnull NSString *)detail;
+ (nonnull instancetype)fileItemDetailWithItemId:(int32_t)itemId
                                           state:(AIFileState)state
                                        selected:(BOOL)selected
                                           title:(nonnull NSString *)title
                                          detail:(nonnull NSString *)detail;

@property (nonatomic, readonly) int32_t itemId;

@property (nonatomic, readonly) AIFileState state;

@property (nonatomic, readonly) BOOL selected;

@property (nonatomic, readonly, nonnull) NSString * title;

@property (nonatomic, readonly, nonnull) NSString * detail;

@end
