// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIField.h"


@implementation AIField

- (nonnull instancetype)initWithRect:(nonnull AIBlock *)rect
                             fieldId:(int32_t)fieldId
                               dataT:(AIDataType)dataT
                              fieldT:(AIFieldType)fieldT
                               title:(nonnull NSString *)title
                            required:(BOOL)required
                               style:(nonnull AIStyle *)style
{
    if (self = [super init]) {
        _rect = rect;
        _fieldId = fieldId;
        _dataT = dataT;
        _fieldT = fieldT;
        _title = [title copy];
        _required = required;
        _style = style;
    }
    return self;
}

+ (nonnull instancetype)fieldWithRect:(nonnull AIBlock *)rect
                              fieldId:(int32_t)fieldId
                                dataT:(AIDataType)dataT
                               fieldT:(AIFieldType)fieldT
                                title:(nonnull NSString *)title
                             required:(BOOL)required
                                style:(nonnull AIStyle *)style
{
    return [[self alloc] initWithRect:rect
                              fieldId:fieldId
                                dataT:dataT
                               fieldT:fieldT
                                title:title
                             required:required
                                style:style];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p rect:%@ fieldId:%@ dataT:%@ fieldT:%@ title:%@ required:%@ style:%@>", self.class, (void *)self, self.rect, @(self.fieldId), @(self.dataT), @(self.fieldT), self.title, @(self.required), self.style];
}

@end
