// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, AIFieldType)
{
    AIFieldTypeInput,
    AIFieldTypeLabel,
    AIFieldTypeExpand,
    AIFieldTypeBack,
    AIFieldTypeError,
    AIFieldTypeChat,
    AIFieldTypeConsole,
    AIFieldTypeLink,
    AIFieldTypeButton,
    AIFieldTypeLogo,
    AIFieldTypePanelBreak,
    AIFieldTypeVerticalSpace,
    AIFieldTypeHelp,
};
