// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFilesDetail.h"
#include "files_detail.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIFilesDetail;

namespace djinni_generated {

struct FilesDetail
{
    using CppType = ::ai::FilesDetail;
    using ObjcType = AIFilesDetail*;

    using Boxed = FilesDetail;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
