// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIField.h"
#include "field.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIField;

namespace djinni_generated {

struct Field
{
    using CppType = ::ai::Field;
    using ObjcType = AIField*;

    using Boxed = Field;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
