// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFilesDetail.h"


@implementation AIFilesDetail

- (nonnull instancetype)initWithIds:(nonnull NSArray<NSNumber *> *)ids
                             titles:(nonnull NSArray<NSNumber *> *)titles
                              sizes:(nonnull NSArray<NSNumber *> *)sizes
                        percentages:(nonnull NSArray<NSNumber *> *)percentages
                             states:(nonnull NSArray<NSNumber *> *)states
                         thumbnails:(nonnull NSArray<NSData *> *)thumbnails
{
    if (self = [super init]) {
        _ids = [ids copy];
        _titles = [titles copy];
        _sizes = [sizes copy];
        _percentages = [percentages copy];
        _states = [states copy];
        _thumbnails = [thumbnails copy];
    }
    return self;
}

+ (nonnull instancetype)filesDetailWithIds:(nonnull NSArray<NSNumber *> *)ids
                                    titles:(nonnull NSArray<NSNumber *> *)titles
                                     sizes:(nonnull NSArray<NSNumber *> *)sizes
                               percentages:(nonnull NSArray<NSNumber *> *)percentages
                                    states:(nonnull NSArray<NSNumber *> *)states
                                thumbnails:(nonnull NSArray<NSData *> *)thumbnails
{
    return [[self alloc] initWithIds:ids
                              titles:titles
                               sizes:sizes
                         percentages:percentages
                              states:states
                          thumbnails:thumbnails];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p ids:%@ titles:%@ sizes:%@ percentages:%@ states:%@ thumbnails:%@>", self.class, (void *)self, self.ids, self.titles, self.sizes, self.percentages, self.states, self.thumbnails];
}

@end
