// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, AIFileState)
{
    AIFileStateNormal,
    AIFileStateDownloading,
    AIFileStateUploading,
    AIFileStateFailed,
    AIFileStateLocal,
    AIFileStateDeleting,
    AIFileStateDeleted,
};
