// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFileState.h"
#import <Foundation/Foundation.h>

@interface AIFilesDetail : NSObject
- (nonnull instancetype)initWithIds:(nonnull NSArray<NSNumber *> *)ids
                             titles:(nonnull NSArray<NSNumber *> *)titles
                              sizes:(nonnull NSArray<NSNumber *> *)sizes
                        percentages:(nonnull NSArray<NSNumber *> *)percentages
                             states:(nonnull NSArray<NSNumber *> *)states
                         thumbnails:(nonnull NSArray<NSData *> *)thumbnails;
+ (nonnull instancetype)filesDetailWithIds:(nonnull NSArray<NSNumber *> *)ids
                                    titles:(nonnull NSArray<NSNumber *> *)titles
                                     sizes:(nonnull NSArray<NSNumber *> *)sizes
                               percentages:(nonnull NSArray<NSNumber *> *)percentages
                                    states:(nonnull NSArray<NSNumber *> *)states
                                thumbnails:(nonnull NSArray<NSData *> *)thumbnails;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * ids;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * titles;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * sizes;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * percentages;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * states;

@property (nonatomic, readonly, nonnull) NSArray<NSData *> * thumbnails;

@end
