// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "form_viewmodel.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIFormViewmodel;

namespace djinni_generated {

class FormViewmodel
{
public:
    using CppType = std::shared_ptr<::ai::FormViewmodel>;
    using CppOptType = std::shared_ptr<::ai::FormViewmodel>;
    using ObjcType = AIFormViewmodel*;

    using Boxed = FormViewmodel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

