// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>
@protocol AIFolderView;


@interface AIFolderViewmodel : NSObject

- (void)onLoad:(nullable id<AIFolderView>)view;

- (int32_t)folderId;

- (nonnull NSData *)listThumbnailContent:(int32_t)row;

- (BOOL)listSelected:(int32_t)section
                 row:(int32_t)row;

- (void)listAction:(int32_t)section
               row:(int32_t)row
          subIndex:(int32_t)subIndex;

- (void)uploadFileOnly:(nonnull NSString *)filename
                  path:(nonnull NSString *)path
             thumbnail:(nonnull NSData *)thumbnail;

- (void)uploadFilesOnly:(nonnull NSArray<NSString *> *)filenames
                  paths:(nonnull NSArray<NSString *> *)paths
             thumbnails:(nonnull NSArray<NSData *> *)thumbnails;

@end
