// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFolderItemDetail+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto FolderItemDetail::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.itemId),
            ::djinni::Bool::toCpp(obj.selected),
            ::djinni::String::toCpp(obj.title)};
}

auto FolderItemDetail::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIFolderItemDetail alloc] initWithItemId:(::djinni::I32::fromCpp(cpp.item_id))
                                             selected:(::djinni::Bool::fromCpp(cpp.selected))
                                                title:(::djinni::String::fromCpp(cpp.title))];
}

}  // namespace djinni_generated
