// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFileItemDetail.h"
#import "AIFolderItemDetail.h"
#import "AIStateChange.h"
#import <Foundation/Foundation.h>
@class AIFolderViewmodel;
@class AIFormViewmodel;
@class AIPreViewmodel;


@protocol AIFolderView

- (void)createFolderView:(nullable AIFolderViewmodel *)folderVm
                  formVm:(nullable AIFormViewmodel *)formVm;

- (void)createPhotoPreview:(nullable AIPreViewmodel *)vm
                  fileName:(nonnull NSString *)fileName
                  filePath:(nonnull NSString *)filePath;

- (void)createVideoPreview:(nullable AIPreViewmodel *)vm
                  fileName:(nonnull NSString *)fileName
                  filePath:(nonnull NSString *)filePath;

- (void)createTextPreview:(nullable AIPreViewmodel *)vm
                 fileName:(nonnull NSString *)fileName
                 filePath:(nonnull NSString *)filePath;

- (void)reload:(int32_t)section
           row:(int32_t)row;

- (void)onReset:(nonnull NSArray<AIFolderItemDetail *> *)folders
          files:(nonnull NSArray<AIFileItemDetail *> *)files;

- (void)onFileStatesChange:(nonnull NSArray<AIStateChange *> *)stateChanges;

- (void)onFileRemove:(int32_t)row;

- (void)onFolderRemove:(int32_t)row;

- (void)onFileDetailChange:(int32_t)row
                    detail:(nonnull NSString *)detail;

- (void)onClearSelection:(nonnull NSArray<NSNumber *> *)folderIndexes
             fileIndexes:(nonnull NSArray<NSNumber *> *)fileIndexes;

- (void)onFileChange:(int32_t)row
                item:(nonnull AIFileItemDetail *)item;

- (void)onFolderChange:(int32_t)row
                  item:(nonnull AIFolderItemDetail *)item;

- (void)onSelectAll;

- (void)onFileSelect:(int32_t)row
            selected:(BOOL)selected;

- (void)onFolderSelect:(int32_t)row
              selected:(BOOL)selected;

- (void)onFileAdded:(int32_t)row
               item:(nonnull AIFileItemDetail *)item;

- (void)onFolderAdded:(int32_t)row
                 item:(nonnull AIFolderItemDetail *)item;

@end
