// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFolderItemDetail.h"


@implementation AIFolderItemDetail

- (nonnull instancetype)initWithItemId:(int32_t)itemId
                              selected:(BOOL)selected
                                 title:(nonnull NSString *)title
{
    if (self = [super init]) {
        _itemId = itemId;
        _selected = selected;
        _title = [title copy];
    }
    return self;
}

+ (nonnull instancetype)folderItemDetailWithItemId:(int32_t)itemId
                                          selected:(BOOL)selected
                                             title:(nonnull NSString *)title
{
    return [[self alloc] initWithItemId:itemId
                               selected:selected
                                  title:title];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p itemId:%@ selected:%@ title:%@>", self.class, (void *)self, @(self.itemId), @(self.selected), self.title];
}

@end
