// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIField.h"
#import <Foundation/Foundation.h>
@protocol AIFormView;
@protocol AIGenericForm;


@interface AIFormViewmodel : NSObject

- (void)action:(int32_t)elementId;

- (void)back;

- (nonnull NSArray<AIField *> *)fields;

- (void)onLoad:(nullable id<AIFormView>)view
          form:(nullable id<AIGenericForm>)form;

- (BOOL)hideNavigation;

- (BOOL)holdonToVm;

@end
