// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFolderItemDetail.h"
#include "folder_item_detail.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIFolderItemDetail;

namespace djinni_generated {

struct FolderItemDetail
{
    using CppType = ::ai::FolderItemDetail;
    using ObjcType = AIFolderItemDetail*;

    using Boxed = FolderItemDetail;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
