// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>

@interface AIFolderItemDetail : NSObject
- (nonnull instancetype)initWithItemId:(int32_t)itemId
                              selected:(BOOL)selected
                                 title:(nonnull NSString *)title;
+ (nonnull instancetype)folderItemDetailWithItemId:(int32_t)itemId
                                          selected:(BOOL)selected
                                             title:(nonnull NSString *)title;

@property (nonatomic, readonly) int32_t itemId;

@property (nonatomic, readonly) BOOL selected;

@property (nonatomic, readonly, nonnull) NSString * title;

@end
