// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFormView+Private.h"
#import "AIFormView.h"
#import "AIFormViewmodel+Private.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class FormView::ObjcProxy final
: public ::ai::FormView
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::FormView;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void replace_form(const std::shared_ptr<::ai::FormViewmodel> & c_vm) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() replaceForm:(::djinni_generated::FormViewmodel::fromCpp(c_vm))];
        }
    }
    void push_form(const std::shared_ptr<::ai::FormViewmodel> & c_vm) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() pushForm:(::djinni_generated::FormViewmodel::fromCpp(c_vm))];
        }
    }
    void set_screen_name(const std::string & c_title) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() setScreenName:(::djinni::String::fromCpp(c_title))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto FormView::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto FormView::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
