// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#include "generic_form.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol AIGenericForm;

namespace djinni_generated {

class GenericForm
{
public:
    using CppType = std::shared_ptr<::ai::GenericForm>;
    using CppOptType = std::shared_ptr<::ai::GenericForm>;
    using ObjcType = id<AIGenericForm>;

    using Boxed = GenericForm;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

