// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import <Foundation/Foundation.h>


@protocol AIGenericForm

- (nonnull NSString *)inputGet:(int32_t)inputId;

- (void)inputSet:(int32_t)inputId
           value:(nonnull NSString *)value;

- (void)inputConfigure:(int32_t)inputId
                config:(nonnull NSString *)config;

- (BOOL)enable:(int32_t)elementId
       enabled:(BOOL)enabled;

- (void)error:(int32_t)elementId
      message:(nonnull NSString *)message;

- (void)close;

- (BOOL)validate;

- (void)disableActions;

- (void)showMessage:(nonnull NSString *)message;

@end
