// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>

@interface AIHeader : NSObject
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                               value:(nonnull NSString *)value;
+ (nonnull instancetype)headerWithName:(nonnull NSString *)name
                                 value:(nonnull NSString *)value;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSString * value;

@end
