// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIHeader.h"
#include "header.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIHeader;

namespace djinni_generated {

struct Header
{
    using CppType = ::ai::Header;
    using ObjcType = AIHeader*;

    using Boxed = Header;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
