// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIHeader.h"


@implementation AIHeader

- (nonnull instancetype)initWithName:(nonnull NSString *)name
                               value:(nonnull NSString *)value
{
    if (self = [super init]) {
        _name = [name copy];
        _value = [value copy];
    }
    return self;
}

+ (nonnull instancetype)headerWithName:(nonnull NSString *)name
                                 value:(nonnull NSString *)value
{
    return [[self alloc] initWithName:name
                                value:value];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p name:%@ value:%@>", self.class, (void *)self, self.name, self.value];
}

@end
