// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIHeader.h"
#import <Foundation/Foundation.h>


@interface AIHttpResult : NSObject

- (void)onResult:(int32_t)statusCode
         headers:(nonnull NSArray<AIHeader *> *)headers
            data:(nonnull NSString *)data;

@end
