// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>


@interface AIIntResult : NSObject

- (void)onResult:(int32_t)value;

@end
