// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIIntResult+Private.h"
#import "AIIntResult.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface AIIntResult ()

- (id)initWithCpp:(const std::shared_ptr<::ai::IntResult>&)cppRef;

@end

@implementation AIIntResult {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ai::IntResult>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ai::IntResult>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onResult:(int32_t)value {
    try {
        _cppRefHandle.get()->on_result(::djinni::I32::toCpp(value));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto IntResult::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto IntResult::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<AIIntResult>(cpp);
}

}  // namespace djinni_generated

@end
