// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>


@interface AILongResult : NSObject

- (void)onResult:(int64_t)size;

@end
