// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AILongResult+Private.h"
#import "AILongResult.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface AILongResult ()

- (id)initWithCpp:(const std::shared_ptr<::ai::LongResult>&)cppRef;

@end

@implementation AILongResult {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ai::LongResult>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ai::LongResult>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onResult:(int64_t)size {
    try {
        _cppRefHandle.get()->on_result(::djinni::I64::toCpp(size));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto LongResult::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto LongResult::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<AILongResult>(cpp);
}

}  // namespace djinni_generated

@end
