// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, AILogType)
{
    AILogTypeLverbose,
    AILogTypeLdebug,
    AILogTypeLinfo,
    AILogTypeLwarning,
    AILogTypeLerror,
};
