// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIMessage.h"


@implementation AIMessage

- (nonnull instancetype)initWithField:(int32_t)field
                              content:(nonnull NSString *)content
{
    if (self = [super init]) {
        _field = field;
        _content = [content copy];
    }
    return self;
}

+ (nonnull instancetype)messageWithField:(int32_t)field
                                 content:(nonnull NSString *)content
{
    return [[self alloc] initWithField:field
                               content:content];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p field:%@ content:%@>", self.class, (void *)self, @(self.field), self.content];
}

@end
