// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIMessage.h"
#include "message.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIMessage;

namespace djinni_generated {

struct Message
{
    using CppType = ::ai::Message;
    using ObjcType = AIMessage*;

    using Boxed = Message;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
