// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>

@interface AIMessage : NSObject
- (nonnull instancetype)initWithField:(int32_t)field
                              content:(nonnull NSString *)content;
+ (nonnull instancetype)messageWithField:(int32_t)field
                                 content:(nonnull NSString *)content;

@property (nonatomic, readonly) int32_t field;

@property (nonatomic, readonly, nonnull) NSString * content;

@end
