// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIMessage+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Message::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.field),
            ::djinni::String::toCpp(obj.content)};
}

auto Message::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIMessage alloc] initWithField:(::djinni::I32::fromCpp(cpp.field))
                                    content:(::djinni::String::fromCpp(cpp.content))];
}

}  // namespace djinni_generated
