// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIFileType.h"
#import "AIHeader.h"
#import "AIHttpVerb.h"
#import "AILogType.h"
#import <Foundation/Foundation.h>
@class AIBinaryResult;
@class AIBoolResult;
@class AIHttpProgressResult;
@class AIHttpResult;
@class AILongResult;
@class AIStringResult;
@class AIStringsResult;
@class AIVoidResult;
@protocol AICancellationToken;


@protocol AIOsIo

- (void)log:(AILogType)type
       line:(int32_t)line
       file:(nonnull NSString *)file
    message:(nonnull NSString *)message;

- (void)logLines:(AILogType)type
            line:(int32_t)line
            file:(nonnull NSString *)file
        messages:(nonnull NSArray<NSString *> *)messages;

- (void)fileReadall:(nonnull NSString *)path
             result:(nullable AIBinaryResult *)result;

- (void)fileWriteall:(nonnull NSString *)path
             content:(nonnull NSData *)content
              result:(nullable AIBoolResult *)result;

- (void)fileWriteallSafely:(nonnull NSString *)path
                   content:(nonnull NSData *)content
                    result:(nullable AIBoolResult *)result;

- (void)fileWritePassword:(nonnull NSString *)username
                 password:(nonnull NSString *)password
                   result:(nullable AIBoolResult *)result;

- (void)fileReadPassword:(nonnull NSString *)username
                  result:(nullable AIStringResult *)result;

- (void)fileSize:(nonnull NSString *)path
          result:(nullable AILongResult *)result;

- (BOOL)fileThumbnail:(nonnull NSString *)path
                 type:(AIFileType)type
               result:(nullable AIBinaryResult *)result;

- (void)copyFile:(nonnull NSString *)currentPath
         newPath:(nonnull NSString *)newPath
          result:(nullable AIBoolResult *)result;

- (void)makePath:(nonnull NSString *)path
          result:(nullable AIBoolResult *)result;

- (void)renameFile:(nonnull NSString *)currentPath
           newPath:(nonnull NSString *)newPath
            result:(nullable AIBoolResult *)result;

- (nullable id<AICancellationToken>)httpRequest:(AIHttpVerb)verb
                                            url:(nonnull NSString *)url
                                        headers:(nonnull NSArray<AIHeader *> *)headers
                                           body:(nonnull NSString *)body
                                         result:(nullable AIHttpResult *)result;

- (nullable id<AICancellationToken>)httpUploadFile:(AIHttpVerb)verb
                                               url:(nonnull NSString *)url
                                          filePath:(nonnull NSString *)filePath
                                           headers:(nonnull NSArray<AIHeader *> *)headers
                                            result:(nullable AIHttpProgressResult *)result;

- (nullable id<AICancellationToken>)httpDownloadFile:(nonnull NSString *)url
                                            filePath:(nonnull NSString *)filePath
                                             headers:(nonnull NSArray<AIHeader *> *)headers
                                                size:(int64_t)size
                                                 md5:(nonnull NSString *)md5
                                              result:(nullable AIHttpProgressResult *)result;

- (void)wait:(int32_t)millis
      result:(nullable AIVoidResult *)result;

- (void)fileExpandDirectories:(nonnull NSArray<NSString *> *)paths
                       result:(nullable AIStringsResult *)result;

- (void)fileCopyHierarchy:(nonnull NSString *)destRootPath
        destRelativePaths:(nonnull NSArray<NSString *> *)destRelativePaths
                 srcPaths:(nonnull NSArray<NSString *> *)srcPaths;

- (void)fileClearCache:(nonnull NSString *)username
                result:(nullable AIBoolResult *)result;

@end
