// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "os_io.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol AIOsIo;

namespace djinni_generated {

class OsIo
{
public:
    using CppType = std::shared_ptr<::ai::OsIo>;
    using CppOptType = std::shared_ptr<::ai::OsIo>;
    using ObjcType = id<AIOsIo>;

    using Boxed = OsIo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

