// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#import "AIMessage.h"
#import "AIStatus.h"
#import <Foundation/Foundation.h>


@protocol AIOsForm

- (void)actionResult:(AIStatus)outcome
               lines:(nonnull NSArray<AIMessage *> *)lines;

- (void)progress:(int32_t)position
           total:(int32_t)total;

- (void)enable:(int32_t)group;

- (void)disable:(int32_t)group;

- (nonnull NSDictionary<NSNumber *, NSString *> *)input;

@end
