// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "os_gui.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol AIOsGui;

namespace djinni_generated {

class OsGui
{
public:
    using CppType = std::shared_ptr<::ai::OsGui>;
    using CppOptType = std::shared_ptr<::ai::OsGui>;
    using ObjcType = id<AIOsGui>;

    using Boxed = OsGui;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

