// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#include "os_form.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol AIOsForm;

namespace djinni_generated {

class OsForm
{
public:
    using CppType = std::shared_ptr<::ai::OsForm>;
    using CppOptType = std::shared_ptr<::ai::OsForm>;
    using ObjcType = id<AIOsForm>;

    using Boxed = OsForm;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

