// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIElement.h"
#import "AIFileType.h"
#import <Foundation/Foundation.h>
@class AIIntResult;
@class AIVoidResult;
@protocol AIOsForm;


@protocol AIOsGui

- (void)showCloudstore;

- (void)guiThread:(nullable AIVoidResult *)cb;

- (void)back;

- (void)openLinkInBrowser:(nonnull NSString *)url;

- (nullable id<AIOsForm>)createForm:(nonnull NSString *)title
                     startHierarchy:(BOOL)startHierarchy
                              width:(int32_t)width
                             height:(int32_t)height
                             action:(nullable AIIntResult *)action
                           elements:(nonnull NSArray<AIElement *> *)elements;

- (void)showMessage:(nonnull NSString *)message;

- (void)preview:(AIFileType)type
           path:(nonnull NSString *)path
         fileId:(int32_t)fileId
       fileName:(nonnull NSString *)fileName;

- (void)reset;

@end
