// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "portal.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIPortal;

namespace djinni_generated {

class Portal
{
public:
    using CppType = std::shared_ptr<::ai::Portal>;
    using CppOptType = std::shared_ptr<::ai::Portal>;
    using ObjcType = AIPortal*;

    using Boxed = Portal;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

