// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIProgress.h"
#include "progress.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIProgress;

namespace djinni_generated {

struct Progress
{
    using CppType = ::ai::Progress;
    using ObjcType = AIProgress*;

    using Boxed = Progress;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
