// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIProduct.h"


@implementation AIProduct

- (nonnull instancetype)initWithProductId:(nonnull NSString *)productId
                                    title:(nonnull NSString *)title
                       productDescription:(nonnull NSString *)productDescription
                                    price:(float)price
                           formattedPrice:(nonnull NSString *)formattedPrice
{
    if (self = [super init]) {
        _productId = [productId copy];
        _title = [title copy];
        _productDescription = [productDescription copy];
        _price = price;
        _formattedPrice = [formattedPrice copy];
    }
    return self;
}

+ (nonnull instancetype)productWithProductId:(nonnull NSString *)productId
                                       title:(nonnull NSString *)title
                          productDescription:(nonnull NSString *)productDescription
                                       price:(float)price
                              formattedPrice:(nonnull NSString *)formattedPrice
{
    return [[self alloc] initWithProductId:productId
                                     title:title
                        productDescription:productDescription
                                     price:price
                            formattedPrice:formattedPrice];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p productId:%@ title:%@ productDescription:%@ price:%@ formattedPrice:%@>", self.class, (void *)self, self.productId, self.title, self.productDescription, @(self.price), self.formattedPrice];
}

@end
