// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIProgress.h"


@implementation AIProgress

- (nonnull instancetype)initWithCount:(int64_t)count
                                total:(int64_t)total
{
    if (self = [super init]) {
        _count = count;
        _total = total;
    }
    return self;
}

+ (nonnull instancetype)progressWithCount:(int64_t)count
                                    total:(int64_t)total
{
    return [[self alloc] initWithCount:count
                                 total:total];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p count:%@ total:%@>", self.class, (void *)self, @(self.count), @(self.total)];
}

@end
