// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIProduct.h"
#include "product.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIProduct;

namespace djinni_generated {

struct Product
{
    using CppType = ::ai::Product;
    using ObjcType = AIProduct*;

    using Boxed = Product;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
