// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>

@interface AIProgress : NSObject
- (nonnull instancetype)initWithCount:(int64_t)count
                                total:(int64_t)total;
+ (nonnull instancetype)progressWithCount:(int64_t)count
                                    total:(int64_t)total;

@property (nonatomic, readonly) int64_t count;

@property (nonatomic, readonly) int64_t total;

@end
