// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIProduct+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Product::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.productId),
            ::djinni::String::toCpp(obj.title),
            ::djinni::String::toCpp(obj.productDescription),
            ::djinni::F32::toCpp(obj.price),
            ::djinni::String::toCpp(obj.formattedPrice)};
}

auto Product::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIProduct alloc] initWithProductId:(::djinni::String::fromCpp(cpp.product_id))
                                          title:(::djinni::String::fromCpp(cpp.title))
                             productDescription:(::djinni::String::fromCpp(cpp.product_description))
                                          price:(::djinni::F32::fromCpp(cpp.price))
                                 formattedPrice:(::djinni::String::fromCpp(cpp.formatted_price))];
}

}  // namespace djinni_generated
