// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIProgress+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Progress::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.count),
            ::djinni::I64::toCpp(obj.total)};
}

auto Progress::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIProgress alloc] initWithCount:(::djinni::I64::fromCpp(cpp.count))
                                       total:(::djinni::I64::fromCpp(cpp.total))];
}

}  // namespace djinni_generated
