// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIReference+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Reference::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.name),
            ::djinni::List<::djinni::String>::toCpp(obj.items)};
}

auto Reference::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIReference alloc] initWithName:(::djinni::String::fromCpp(cpp.name))
                                       items:(::djinni::List<::djinni::String>::fromCpp(cpp.items))];
}

}  // namespace djinni_generated
