// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIReference.h"
#include "reference.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIReference;

namespace djinni_generated {

struct Reference
{
    using CppType = ::ai::Reference;
    using ObjcType = AIReference*;

    using Boxed = Reference;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
