// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIReference.h"


@implementation AIReference

- (nonnull instancetype)initWithName:(nonnull NSString *)name
                               items:(nonnull NSArray<NSString *> *)items
{
    if (self = [super init]) {
        _name = [name copy];
        _items = [items copy];
    }
    return self;
}

+ (nonnull instancetype)referenceWithName:(nonnull NSString *)name
                                    items:(nonnull NSArray<NSString *> *)items
{
    return [[self alloc] initWithName:name
                                items:items];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p name:%@ items:%@>", self.class, (void *)self, self.name, self.items];
}

@end
