// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "root_viewmodel.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIRootViewmodel;

namespace djinni_generated {

class RootViewmodel
{
public:
    using CppType = std::shared_ptr<::ai::RootViewmodel>;
    using CppOptType = std::shared_ptr<::ai::RootViewmodel>;
    using ObjcType = AIRootViewmodel*;

    using Boxed = RootViewmodel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

