// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIScreenType.h"
#import <Foundation/Foundation.h>
@class AIRootViewmodel;
@protocol AIDiagnostic;
@protocol AIOsIo;
@protocol AIUiCallback;
@protocol AIView;
@protocol AIWorker;


@interface AIRootViewmodel : NSObject

+ (nullable AIRootViewmodel *)create:(nullable id<AIWorker>)scheduler
                     appDataLocation:(nonnull NSString *)appDataLocation
                             thumbPx:(int32_t)thumbPx
                                  io:(nullable id<AIOsIo>)io
                                view:(nullable id<AIView>)view
                                type:(AIScreenType)type
                            callback:(nullable id<AIUiCallback>)callback
                              logger:(nullable id<AIDiagnostic>)logger;

@end
