// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIStyle.h"


@implementation AIStyle

- (nonnull instancetype)initWithSize:(AISize)size
                               align:(AIAlign)align
                              colour:(AIColour)colour
                              weight:(AIWeight)weight
                               width:(int32_t)width
{
    if (self = [super init]) {
        _size = size;
        _align = align;
        _colour = colour;
        _weight = weight;
        _width = width;
    }
    return self;
}

+ (nonnull instancetype)styleWithSize:(AISize)size
                                align:(AIAlign)align
                               colour:(AIColour)colour
                               weight:(AIWeight)weight
                                width:(int32_t)width
{
    return [[self alloc] initWithSize:size
                                align:align
                               colour:colour
                               weight:weight
                                width:width];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p size:%@ align:%@ colour:%@ weight:%@ width:%@>", self.class, (void *)self, @(self.size), @(self.align), @(self.colour), @(self.weight), @(self.width)];
}

@end
