// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>


@interface AIStringResult : NSObject

- (void)onResult:(nonnull NSString *)content;

@end
