// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIStateChange+Private.h"
#import "AIFileState+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto StateChange::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.index),
            ::djinni::Enum<::ai::FileState, AIFileState>::toCpp(obj.state)};
}

auto StateChange::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIStateChange alloc] initWithIndex:(::djinni::I32::fromCpp(cpp.index))
                                          state:(::djinni::Enum<::ai::FileState, AIFileState>::fromCpp(cpp.state))];
}

}  // namespace djinni_generated
