// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIStyle+Private.h"
#import "AIAlign+Private.h"
#import "AIColour+Private.h"
#import "AISize+Private.h"
#import "AIWeight+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Style::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Enum<::ai::Size, AISize>::toCpp(obj.size),
            ::djinni::Enum<::ai::Align, AIAlign>::toCpp(obj.align),
            ::djinni::Enum<::ai::Colour, AIColour>::toCpp(obj.colour),
            ::djinni::Enum<::ai::Weight, AIWeight>::toCpp(obj.weight),
            ::djinni::I32::toCpp(obj.width)};
}

auto Style::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIStyle alloc] initWithSize:(::djinni::Enum<::ai::Size, AISize>::fromCpp(cpp.size))
                                   align:(::djinni::Enum<::ai::Align, AIAlign>::fromCpp(cpp.align))
                                  colour:(::djinni::Enum<::ai::Colour, AIColour>::fromCpp(cpp.colour))
                                  weight:(::djinni::Enum<::ai::Weight, AIWeight>::fromCpp(cpp.weight))
                                   width:(::djinni::I32::fromCpp(cpp.width))];
}

}  // namespace djinni_generated
