// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIStyle.h"
#include "style.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIStyle;

namespace djinni_generated {

struct Style
{
    using CppType = ::ai::Style;
    using ObjcType = AIStyle*;

    using Boxed = Style;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
