// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>


@interface AIStringsResult : NSObject

- (void)onResult:(nonnull NSArray<NSString *> *)content;

@end
