// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIProduct.h"
#import "AITransactionDetail.h"
#import <Foundation/Foundation.h>


@interface AIStoreViewmodel : NSObject

- (void)onTransactionStates:(nonnull NSDictionary<NSString *, AITransactionDetail *> *)states;

- (void)onProducts:(nonnull NSArray<AIProduct *> *)products;

- (void)onRestoreFail:(nonnull NSString *)errorMessage;

- (void)onRestoreFinished;

@end
