// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIStringResult+Private.h"
#import "AIStringResult.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface AIStringResult ()

- (id)initWithCpp:(const std::shared_ptr<::ai::StringResult>&)cppRef;

@end

@implementation AIStringResult {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ai::StringResult>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ai::StringResult>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onResult:(nonnull NSString *)content {
    try {
        _cppRefHandle.get()->on_result(::djinni::String::toCpp(content));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto StringResult::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto StringResult::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<AIStringResult>(cpp);
}

}  // namespace djinni_generated

@end
