// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIStateChange.h"


@implementation AIStateChange

- (nonnull instancetype)initWithIndex:(int32_t)index
                                state:(AIFileState)state
{
    if (self = [super init]) {
        _index = index;
        _state = state;
    }
    return self;
}

+ (nonnull instancetype)stateChangeWithIndex:(int32_t)index
                                       state:(AIFileState)state
{
    return [[self alloc] initWithIndex:index
                                 state:state];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p index:%@ state:%@>", self.class, (void *)self, @(self.index), @(self.state)];
}

@end
