// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIStateChange.h"
#include "state_change.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIStateChange;

namespace djinni_generated {

struct StateChange
{
    using CppType = ::ai::StateChange;
    using ObjcType = AIStateChange*;

    using Boxed = StateChange;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
