// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "strings_result.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class AIStringsResult;

namespace djinni_generated {

class StringsResult
{
public:
    using CppType = std::shared_ptr<::ai::StringsResult>;
    using CppOptType = std::shared_ptr<::ai::StringsResult>;
    using ObjcType = AIStringsResult*;

    using Boxed = StringsResult;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

