// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#import "AIAlign.h"
#import "AIColour.h"
#import "AISize.h"
#import "AIWeight.h"
#import <Foundation/Foundation.h>

@interface AIStyle : NSObject
- (nonnull instancetype)initWithSize:(AISize)size
                               align:(AIAlign)align
                              colour:(AIColour)colour
                              weight:(AIWeight)weight
                               width:(int32_t)width;
+ (nonnull instancetype)styleWithSize:(AISize)size
                                align:(AIAlign)align
                               colour:(AIColour)colour
                               weight:(AIWeight)weight
                                width:(int32_t)width;

@property (nonatomic, readonly) AISize size;

@property (nonatomic, readonly) AIAlign align;

@property (nonatomic, readonly) AIColour colour;

@property (nonatomic, readonly) AIWeight weight;

@property (nonatomic, readonly) int32_t width;

@end
