// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AITransactionState.h"
#import <Foundation/Foundation.h>

@interface AITransactionDetail : NSObject
- (nonnull instancetype)initWithState:(AITransactionState)state
                         errorMessage:(nonnull NSString *)errorMessage;
+ (nonnull instancetype)transactionDetailWithState:(AITransactionState)state
                                      errorMessage:(nonnull NSString *)errorMessage;

@property (nonatomic, readonly) AITransactionState state;

@property (nonatomic, readonly, nonnull) NSString * errorMessage;

@end
