// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AITransactionDetail+Private.h"
#import "AITransactionState+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TransactionDetail::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Enum<::ai::TransactionState, AITransactionState>::toCpp(obj.state),
            ::djinni::String::toCpp(obj.errorMessage)};
}

auto TransactionDetail::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AITransactionDetail alloc] initWithState:(::djinni::Enum<::ai::TransactionState, AITransactionState>::fromCpp(cpp.state))
                                         errorMessage:(::djinni::String::fromCpp(cpp.error_message))];
}

}  // namespace djinni_generated
