// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "ui_callback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol AIUiCallback;

namespace djinni_generated {

class UiCallback
{
public:
    using CppType = std::shared_ptr<::ai::UiCallback>;
    using CppOptType = std::shared_ptr<::ai::UiCallback>;
    using ObjcType = id<AIUiCallback>;

    using Boxed = UiCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

