// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIUiCallback+Private.h"
#import "AIUiCallback.h"
#import "AIVoidResult+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class UiCallback::ObjcProxy final
: public ::ai::UiCallback
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::UiCallback;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void gui_thread(const std::shared_ptr<::ai::VoidResult> & c_cb) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() guiThread:(::djinni_generated::VoidResult::fromCpp(c_cb))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto UiCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto UiCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
