// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>
@class AIVoidResult;


@protocol AIUiCallback

- (void)guiThread:(nullable AIVoidResult *)cb;

@end
