// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "view.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol AIView;

namespace djinni_generated {

class View
{
public:
    using CppType = std::shared_ptr<::ai::View>;
    using CppOptType = std::shared_ptr<::ai::View>;
    using ObjcType = id<AIView>;

    using Boxed = View;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

