// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import "AIWorker+Private.h"
#import "AIWorker.h"
#import "AITask+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class Worker::ObjcProxy final
: public ::ai::Worker
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::Worker;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void schedule(const std::shared_ptr<::ai::Task> & c_todo) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() schedule:(::djinni_generated::Task::fromCpp(c_todo))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto Worker::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto Worker::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
