// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#import <Foundation/Foundation.h>
@class AITask;


@protocol AIWorker

- (void)schedule:(nullable AITask *)todo;

@end
