// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "log_type.hpp"

namespace djinni_generated {

class NativeLogType final : ::djinni::JniEnum {
public:
    using CppType = ::ai::LogType;
    using JniType = jobject;

    using Boxed = NativeLogType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeLogType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeLogType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeLogType() : JniEnum("net/ai/LogType") {}
    friend ::djinni::JniClass<NativeLogType>;
};

}  // namespace djinni_generated
