// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "store_viewmodel.hpp"

namespace djinni_generated {

class NativeStoreViewmodel final : ::djinni::JniInterface<::ai::StoreViewmodel, NativeStoreViewmodel> {
public:
    using CppType = std::shared_ptr<::ai::StoreViewmodel>;
    using CppOptType = std::shared_ptr<::ai::StoreViewmodel>;
    using JniType = jobject;

    using Boxed = NativeStoreViewmodel;

    ~NativeStoreViewmodel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeStoreViewmodel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeStoreViewmodel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeStoreViewmodel();
    friend ::djinni::JniClass<NativeStoreViewmodel>;
    friend ::djinni::JniInterface<::ai::StoreViewmodel, NativeStoreViewmodel>;

};

}  // namespace djinni_generated
