// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "message.hpp"

namespace djinni_generated {

class NativeMessage final {
public:
    using CppType = ::ai::Message;
    using JniType = jobject;

    using Boxed = NativeMessage;

    ~NativeMessage();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeMessage();
    friend ::djinni::JniClass<NativeMessage>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/ai/Message") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILjava/lang/String;)V") };
    const jfieldID field_mField { ::djinni::jniGetFieldID(clazz.get(), "mField", "I") };
    const jfieldID field_mContent { ::djinni::jniGetFieldID(clazz.get(), "mContent", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
