// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeFolderItemDetail.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeFolderItemDetail::NativeFolderItemDetail() = default;

NativeFolderItemDetail::~NativeFolderItemDetail() = default;

auto NativeFolderItemDetail::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeFolderItemDetail>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.item_id)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.selected)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.title)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeFolderItemDetail::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeFolderItemDetail>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mItemId)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mSelected)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mTitle))};
}

}  // namespace djinni_generated
