// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "state_change.hpp"

namespace djinni_generated {

class NativeStateChange final {
public:
    using CppType = ::ai::StateChange;
    using JniType = jobject;

    using Boxed = NativeStateChange;

    ~NativeStateChange();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeStateChange();
    friend ::djinni::JniClass<NativeStateChange>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/ai/StateChange") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILnet/ai/FileState;)V") };
    const jfieldID field_mIndex { ::djinni::jniGetFieldID(clazz.get(), "mIndex", "I") };
    const jfieldID field_mState { ::djinni::jniGetFieldID(clazz.get(), "mState", "Lnet/ai/FileState;") };
};

}  // namespace djinni_generated
