// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "long_result.hpp"

namespace djinni_generated {

class NativeLongResult final : ::djinni::JniInterface<::ai::LongResult, NativeLongResult> {
public:
    using CppType = std::shared_ptr<::ai::LongResult>;
    using CppOptType = std::shared_ptr<::ai::LongResult>;
    using JniType = jobject;

    using Boxed = NativeLongResult;

    ~NativeLongResult();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLongResult>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLongResult>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLongResult();
    friend ::djinni::JniClass<NativeLongResult>;
    friend ::djinni::JniInterface<::ai::LongResult, NativeLongResult>;

};

}  // namespace djinni_generated
