// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeFormView.hpp"  // my header
#include "Marshal.hpp"
#include "NativeFormViewmodel.hpp"

namespace djinni_generated {

NativeFormView::NativeFormView() : ::djinni::JniInterface<::ai::FormView, NativeFormView>() {}

NativeFormView::~NativeFormView() = default;

NativeFormView::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeFormView::JavaProxy::~JavaProxy() = default;

void NativeFormView::JavaProxy::replace_form(const std::shared_ptr<::ai::FormViewmodel> & c_vm) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeFormView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_replaceForm,
                           ::djinni::get(::djinni_generated::NativeFormViewmodel::fromCpp(jniEnv, c_vm)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeFormView::JavaProxy::push_form(const std::shared_ptr<::ai::FormViewmodel> & c_vm) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeFormView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_pushForm,
                           ::djinni::get(::djinni_generated::NativeFormViewmodel::fromCpp(jniEnv, c_vm)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeFormView::JavaProxy::set_screen_name(const std::string & c_title) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeFormView>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setScreenName,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_title)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
