// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeWorker.hpp"  // my header
#include "NativeTask.hpp"

namespace djinni_generated {

NativeWorker::NativeWorker() : ::djinni::JniInterface<::ai::Worker, NativeWorker>() {}

NativeWorker::~NativeWorker() = default;

NativeWorker::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeWorker::JavaProxy::~JavaProxy() = default;

void NativeWorker::JavaProxy::schedule(const std::shared_ptr<::ai::Task> & c_todo) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeWorker>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_schedule,
                           ::djinni::get(::djinni_generated::NativeTask::fromCpp(jniEnv, c_todo)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
