// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeStoreViewmodel.hpp"  // my header
#include "Marshal.hpp"
#include "NativeProduct.hpp"
#include "NativeTransactionDetail.hpp"

namespace djinni_generated {

NativeStoreViewmodel::NativeStoreViewmodel() : ::djinni::JniInterface<::ai::StoreViewmodel, NativeStoreViewmodel>("net/ai/StoreViewmodel$CppProxy") {}

NativeStoreViewmodel::~NativeStoreViewmodel() = default;


CJNIEXPORT void JNICALL Java_net_ai_StoreViewmodel_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ai::StoreViewmodel>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_StoreViewmodel_00024CppProxy_native_1onTransactionStates(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_states)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::StoreViewmodel>(nativeRef);
        ref->on_transaction_states(::djinni::Map<::djinni::String, ::djinni_generated::NativeTransactionDetail>::toCpp(jniEnv, j_states));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_StoreViewmodel_00024CppProxy_native_1onProducts(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_products)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::StoreViewmodel>(nativeRef);
        ref->on_products(::djinni::List<::djinni_generated::NativeProduct>::toCpp(jniEnv, j_products));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_StoreViewmodel_00024CppProxy_native_1onRestoreFail(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_errorMessage)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::StoreViewmodel>(nativeRef);
        ref->on_restore_fail(::djinni::String::toCpp(jniEnv, j_errorMessage));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_StoreViewmodel_00024CppProxy_native_1onRestoreFinished(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::StoreViewmodel>(nativeRef);
        ref->on_restore_finished();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
