// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "directories_detail.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDirectoriesDetail final {
public:
    using CppType = ::ai::DirectoriesDetail;
    using JniType = jobject;

    using Boxed = NativeDirectoriesDetail;

    ~NativeDirectoriesDetail();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeDirectoriesDetail();
    friend ::djinni::JniClass<NativeDirectoriesDetail>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/ai/DirectoriesDetail") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;Ljava/util/ArrayList;)V") };
    const jfieldID field_mIds { ::djinni::jniGetFieldID(clazz.get(), "mIds", "Ljava/util/ArrayList;") };
    const jfieldID field_mTitles { ::djinni::jniGetFieldID(clazz.get(), "mTitles", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
