// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "file_type.hpp"

namespace djinni_generated {

class NativeFileType final : ::djinni::JniEnum {
public:
    using CppType = ::ai::FileType;
    using JniType = jobject;

    using Boxed = NativeFileType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeFileType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeFileType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeFileType() : JniEnum("net/ai/FileType") {}
    friend ::djinni::JniClass<NativeFileType>;
};

}  // namespace djinni_generated
