// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeMessage.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeMessage::NativeMessage() = default;

NativeMessage::~NativeMessage() = default;

auto NativeMessage::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeMessage>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.field)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.content)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeMessage::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeMessage>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mField)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mContent))};
}

}  // namespace djinni_generated
