// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeProduct.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeProduct::NativeProduct() = default;

NativeProduct::~NativeProduct() = default;

auto NativeProduct::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeProduct>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.product_id)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.title)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.product_description)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.price)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.formatted_price)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeProduct::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeProduct>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mProductId)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mTitle)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mProductDescription)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mPrice)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mFormattedPrice))};
}

}  // namespace djinni_generated
