// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeStringResult.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeStringResult::NativeStringResult() : ::djinni::JniInterface<::ai::StringResult, NativeStringResult>("net/ai/StringResult$CppProxy") {}

NativeStringResult::~NativeStringResult() = default;


CJNIEXPORT void JNICALL Java_net_ai_StringResult_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ai::StringResult>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_StringResult_00024CppProxy_native_1onResult(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_content)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::StringResult>(nativeRef);
        ref->on_result(::djinni::String::toCpp(jniEnv, j_content));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
