// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include "data_type.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDataType final : ::djinni::JniEnum {
public:
    using CppType = ::ai::DataType;
    using JniType = jobject;

    using Boxed = NativeDataType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeDataType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeDataType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeDataType() : JniEnum("net/ai/DataType") {}
    friend ::djinni::JniClass<NativeDataType>;
};

}  // namespace djinni_generated
