// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include "align.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAlign final : ::djinni::JniEnum {
public:
    using CppType = ::ai::Align;
    using JniType = jobject;

    using Boxed = NativeAlign;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeAlign>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeAlign>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeAlign() : JniEnum("net/ai/Align") {}
    friend ::djinni::JniClass<NativeAlign>;
};

}  // namespace djinni_generated
