// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "bool_result.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBoolResult final : ::djinni::JniInterface<::ai::BoolResult, NativeBoolResult> {
public:
    using CppType = std::shared_ptr<::ai::BoolResult>;
    using CppOptType = std::shared_ptr<::ai::BoolResult>;
    using JniType = jobject;

    using Boxed = NativeBoolResult;

    ~NativeBoolResult();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeBoolResult>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeBoolResult>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeBoolResult();
    friend ::djinni::JniClass<NativeBoolResult>;
    friend ::djinni::JniInterface<::ai::BoolResult, NativeBoolResult>;

};

}  // namespace djinni_generated
