// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include "djinni_support.hpp"
#include "weight.hpp"

namespace djinni_generated {

class NativeWeight final : ::djinni::JniEnum {
public:
    using CppType = ::ai::Weight;
    using JniType = jobject;

    using Boxed = NativeWeight;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeWeight>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeWeight>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeWeight() : JniEnum("net/ai/Weight") {}
    friend ::djinni::JniClass<NativeWeight>;
};

}  // namespace djinni_generated
