// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "pre_viewmodel.hpp"

namespace djinni_generated {

class NativePreViewmodel final : ::djinni::JniInterface<::ai::PreViewmodel, NativePreViewmodel> {
public:
    using CppType = std::shared_ptr<::ai::PreViewmodel>;
    using CppOptType = std::shared_ptr<::ai::PreViewmodel>;
    using JniType = jobject;

    using Boxed = NativePreViewmodel;

    ~NativePreViewmodel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePreViewmodel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePreViewmodel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePreViewmodel();
    friend ::djinni::JniClass<NativePreViewmodel>;
    friend ::djinni::JniInterface<::ai::PreViewmodel, NativePreViewmodel>;

};

}  // namespace djinni_generated
