// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "form_viewmodel.hpp"

namespace djinni_generated {

class NativeFormViewmodel final : ::djinni::JniInterface<::ai::FormViewmodel, NativeFormViewmodel> {
public:
    using CppType = std::shared_ptr<::ai::FormViewmodel>;
    using CppOptType = std::shared_ptr<::ai::FormViewmodel>;
    using JniType = jobject;

    using Boxed = NativeFormViewmodel;

    ~NativeFormViewmodel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeFormViewmodel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeFormViewmodel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeFormViewmodel();
    friend ::djinni::JniClass<NativeFormViewmodel>;
    friend ::djinni::JniInterface<::ai::FormViewmodel, NativeFormViewmodel>;

};

}  // namespace djinni_generated
