// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "binary_result.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBinaryResult final : ::djinni::JniInterface<::ai::BinaryResult, NativeBinaryResult> {
public:
    using CppType = std::shared_ptr<::ai::BinaryResult>;
    using CppOptType = std::shared_ptr<::ai::BinaryResult>;
    using JniType = jobject;

    using Boxed = NativeBinaryResult;

    ~NativeBinaryResult();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeBinaryResult>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeBinaryResult>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeBinaryResult();
    friend ::djinni::JniClass<NativeBinaryResult>;
    friend ::djinni::JniInterface<::ai::BinaryResult, NativeBinaryResult>;

};

}  // namespace djinni_generated
