// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "root_viewmodel.hpp"

namespace djinni_generated {

class NativeRootViewmodel final : ::djinni::JniInterface<::ai::RootViewmodel, NativeRootViewmodel> {
public:
    using CppType = std::shared_ptr<::ai::RootViewmodel>;
    using CppOptType = std::shared_ptr<::ai::RootViewmodel>;
    using JniType = jobject;

    using Boxed = NativeRootViewmodel;

    ~NativeRootViewmodel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRootViewmodel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRootViewmodel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRootViewmodel();
    friend ::djinni::JniClass<NativeRootViewmodel>;
    friend ::djinni::JniInterface<::ai::RootViewmodel, NativeRootViewmodel>;

};

}  // namespace djinni_generated
