// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeHttpProgressResult.hpp"  // my header
#include "Marshal.hpp"
#include "NativeHeader.hpp"
#include "NativeProgress.hpp"

namespace djinni_generated {

NativeHttpProgressResult::NativeHttpProgressResult() : ::djinni::JniInterface<::ai::HttpProgressResult, NativeHttpProgressResult>("net/ai/HttpProgressResult$CppProxy") {}

NativeHttpProgressResult::~NativeHttpProgressResult() = default;


CJNIEXPORT void JNICALL Java_net_ai_HttpProgressResult_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ai::HttpProgressResult>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_HttpProgressResult_00024CppProxy_native_1onProgress(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_at)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::HttpProgressResult>(nativeRef);
        ref->on_progress(::djinni_generated::NativeProgress::toCpp(jniEnv, j_at));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_HttpProgressResult_00024CppProxy_native_1onResult(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_statusCode, jobject j_headers, jlong j_contentLength)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::HttpProgressResult>(nativeRef);
        ref->on_result(::djinni::I32::toCpp(jniEnv, j_statusCode),
                       ::djinni::List<::djinni_generated::NativeHeader>::toCpp(jniEnv, j_headers),
                       ::djinni::I64::toCpp(jniEnv, j_contentLength));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
