// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeStringsResult.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeStringsResult::NativeStringsResult() : ::djinni::JniInterface<::ai::StringsResult, NativeStringsResult>("net/ai/StringsResult$CppProxy") {}

NativeStringsResult::~NativeStringsResult() = default;


CJNIEXPORT void JNICALL Java_net_ai_StringsResult_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ai::StringsResult>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_StringsResult_00024CppProxy_native_1onResult(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_content)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::StringsResult>(nativeRef);
        ref->on_result(::djinni::List<::djinni::String>::toCpp(jniEnv, j_content));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
