// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "folder_item_detail.hpp"

namespace djinni_generated {

class NativeFolderItemDetail final {
public:
    using CppType = ::ai::FolderItemDetail;
    using JniType = jobject;

    using Boxed = NativeFolderItemDetail;

    ~NativeFolderItemDetail();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeFolderItemDetail();
    friend ::djinni::JniClass<NativeFolderItemDetail>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/ai/FolderItemDetail") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(IZLjava/lang/String;)V") };
    const jfieldID field_mItemId { ::djinni::jniGetFieldID(clazz.get(), "mItemId", "I") };
    const jfieldID field_mSelected { ::djinni::jniGetFieldID(clazz.get(), "mSelected", "Z") };
    const jfieldID field_mTitle { ::djinni::jniGetFieldID(clazz.get(), "mTitle", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
