// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeFileItemDetail.hpp"  // my header
#include "Marshal.hpp"
#include "NativeFileState.hpp"

namespace djinni_generated {

NativeFileItemDetail::NativeFileItemDetail() = default;

NativeFileItemDetail::~NativeFileItemDetail() = default;

auto NativeFileItemDetail::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeFileItemDetail>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.item_id)),
                                                           ::djinni::get(::djinni_generated::NativeFileState::fromCpp(jniEnv, c.state)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.selected)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.title)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.detail)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeFileItemDetail::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeFileItemDetail>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mItemId)),
            ::djinni_generated::NativeFileState::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mState)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mSelected)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mTitle)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mDetail))};
}

}  // namespace djinni_generated
