// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "progress.hpp"

namespace djinni_generated {

class NativeProgress final {
public:
    using CppType = ::ai::Progress;
    using JniType = jobject;

    using Boxed = NativeProgress;

    ~NativeProgress();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeProgress();
    friend ::djinni::JniClass<NativeProgress>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/ai/Progress") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(JJ)V") };
    const jfieldID field_mCount { ::djinni::jniGetFieldID(clazz.get(), "mCount", "J") };
    const jfieldID field_mTotal { ::djinni::jniGetFieldID(clazz.get(), "mTotal", "J") };
};

}  // namespace djinni_generated
