// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "portal.hpp"

namespace djinni_generated {

class NativePortal final : ::djinni::JniInterface<::ai::Portal, NativePortal> {
public:
    using CppType = std::shared_ptr<::ai::Portal>;
    using CppOptType = std::shared_ptr<::ai::Portal>;
    using JniType = jobject;

    using Boxed = NativePortal;

    ~NativePortal();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePortal>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePortal>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePortal();
    friend ::djinni::JniClass<NativePortal>;
    friend ::djinni::JniInterface<::ai::Portal, NativePortal>;

};

}  // namespace djinni_generated
