// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#include "NativeBlock.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeBlock::NativeBlock() = default;

NativeBlock::~NativeBlock() = default;

auto NativeBlock::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeBlock>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.row_beg)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.row_end)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.col_beg)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.col_end)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeBlock::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeBlock>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mRowBeg)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mRowEnd)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mColBeg)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mColEnd))};
}

}  // namespace djinni_generated
