// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeUiCallback.hpp"  // my header
#include "NativeVoidResult.hpp"

namespace djinni_generated {

NativeUiCallback::NativeUiCallback() : ::djinni::JniInterface<::ai::UiCallback, NativeUiCallback>() {}

NativeUiCallback::~NativeUiCallback() = default;

NativeUiCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeUiCallback::JavaProxy::~JavaProxy() = default;

void NativeUiCallback::JavaProxy::gui_thread(const std::shared_ptr<::ai::VoidResult> & c_cb) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeUiCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_guiThread,
                           ::djinni::get(::djinni_generated::NativeVoidResult::fromCpp(jniEnv, c_cb)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
