// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#include "NativeField.hpp"  // my header
#include "Marshal.hpp"
#include "NativeBlock.hpp"
#include "NativeDataType.hpp"
#include "NativeFieldType.hpp"
#include "NativeStyle.hpp"

namespace djinni_generated {

NativeField::NativeField() = default;

NativeField::~NativeField() = default;

auto NativeField::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeField>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::NativeBlock::fromCpp(jniEnv, c.rect)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.field_id)),
                                                           ::djinni::get(::djinni_generated::NativeDataType::fromCpp(jniEnv, c.data_t)),
                                                           ::djinni::get(::djinni_generated::NativeFieldType::fromCpp(jniEnv, c.field_t)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.title)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.required)),
                                                           ::djinni::get(::djinni_generated::NativeStyle::fromCpp(jniEnv, c.style)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeField::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 8);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeField>::get();
    return {::djinni_generated::NativeBlock::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mRect)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mFieldId)),
            ::djinni_generated::NativeDataType::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mDataT)),
            ::djinni_generated::NativeFieldType::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mFieldT)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mTitle)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mRequired)),
            ::djinni_generated::NativeStyle::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mStyle))};
}

}  // namespace djinni_generated
