// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeStateChange.hpp"  // my header
#include "Marshal.hpp"
#include "NativeFileState.hpp"

namespace djinni_generated {

NativeStateChange::NativeStateChange() = default;

NativeStateChange::~NativeStateChange() = default;

auto NativeStateChange::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeStateChange>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.index)),
                                                           ::djinni::get(::djinni_generated::NativeFileState::fromCpp(jniEnv, c.state)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeStateChange::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeStateChange>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mIndex)),
            ::djinni_generated::NativeFileState::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mState))};
}

}  // namespace djinni_generated
