// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#pragma once

#include "djinni_support.hpp"
#include "element_type.hpp"

namespace djinni_generated {

class NativeElementType final : ::djinni::JniEnum {
public:
    using CppType = ::ai::ElementType;
    using JniType = jobject;

    using Boxed = NativeElementType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeElementType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeElementType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeElementType() : JniEnum("net/ai/ElementType") {}
    friend ::djinni::JniClass<NativeElementType>;
};

}  // namespace djinni_generated
