// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "cancellation_token.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCancellationToken final : ::djinni::JniInterface<::ai::CancellationToken, NativeCancellationToken> {
public:
    using CppType = std::shared_ptr<::ai::CancellationToken>;
    using CppOptType = std::shared_ptr<::ai::CancellationToken>;
    using JniType = jobject;

    using Boxed = NativeCancellationToken;

    ~NativeCancellationToken();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCancellationToken>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCancellationToken>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCancellationToken();
    friend ::djinni::JniClass<NativeCancellationToken>;
    friend ::djinni::JniInterface<::ai::CancellationToken, NativeCancellationToken>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::ai::CancellationToken
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void cancel() override;

    private:
        friend ::djinni::JniInterface<::ai::CancellationToken, ::djinni_generated::NativeCancellationToken>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/ai/CancellationToken") };
    const jmethodID method_cancel { ::djinni::jniGetMethodID(clazz.get(), "cancel", "()V") };
};

}  // namespace djinni_generated
