// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "http_progress_result.hpp"

namespace djinni_generated {

class NativeHttpProgressResult final : ::djinni::JniInterface<::ai::HttpProgressResult, NativeHttpProgressResult> {
public:
    using CppType = std::shared_ptr<::ai::HttpProgressResult>;
    using CppOptType = std::shared_ptr<::ai::HttpProgressResult>;
    using JniType = jobject;

    using Boxed = NativeHttpProgressResult;

    ~NativeHttpProgressResult();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeHttpProgressResult>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeHttpProgressResult>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeHttpProgressResult();
    friend ::djinni::JniClass<NativeHttpProgressResult>;
    friend ::djinni::JniInterface<::ai::HttpProgressResult, NativeHttpProgressResult>;

};

}  // namespace djinni_generated
