// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "void_result.hpp"

namespace djinni_generated {

class NativeVoidResult final : ::djinni::JniInterface<::ai::VoidResult, NativeVoidResult> {
public:
    using CppType = std::shared_ptr<::ai::VoidResult>;
    using CppOptType = std::shared_ptr<::ai::VoidResult>;
    using JniType = jobject;

    using Boxed = NativeVoidResult;

    ~NativeVoidResult();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVoidResult>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVoidResult>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVoidResult();
    friend ::djinni::JniClass<NativeVoidResult>;
    friend ::djinni::JniInterface<::ai::VoidResult, NativeVoidResult>;

};

}  // namespace djinni_generated
