// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include "djinni_support.hpp"
#include "field_type.hpp"

namespace djinni_generated {

class NativeFieldType final : ::djinni::JniEnum {
public:
    using CppType = ::ai::FieldType;
    using JniType = jobject;

    using Boxed = NativeFieldType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeFieldType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeFieldType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeFieldType() : JniEnum("net/ai/FieldType") {}
    friend ::djinni::JniClass<NativeFieldType>;
};

}  // namespace djinni_generated
