// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#include "NativeStyle.hpp"  // my header
#include "Marshal.hpp"
#include "NativeAlign.hpp"
#include "NativeColour.hpp"
#include "NativeSize.hpp"
#include "NativeWeight.hpp"

namespace djinni_generated {

NativeStyle::NativeStyle() = default;

NativeStyle::~NativeStyle() = default;

auto NativeStyle::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeStyle>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::NativeSize::fromCpp(jniEnv, c.size)),
                                                           ::djinni::get(::djinni_generated::NativeAlign::fromCpp(jniEnv, c.align)),
                                                           ::djinni::get(::djinni_generated::NativeColour::fromCpp(jniEnv, c.colour)),
                                                           ::djinni::get(::djinni_generated::NativeWeight::fromCpp(jniEnv, c.weight)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.width)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeStyle::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeStyle>::get();
    return {::djinni_generated::NativeSize::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mSize)),
            ::djinni_generated::NativeAlign::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mAlign)),
            ::djinni_generated::NativeColour::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mColour)),
            ::djinni_generated::NativeWeight::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mWeight)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mWidth))};
}

}  // namespace djinni_generated
