// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativePreViewmodel.hpp"  // my header

namespace djinni_generated {

NativePreViewmodel::NativePreViewmodel() : ::djinni::JniInterface<::ai::PreViewmodel, NativePreViewmodel>("net/ai/PreViewmodel$CppProxy") {}

NativePreViewmodel::~NativePreViewmodel() = default;


CJNIEXPORT void JNICALL Java_net_ai_PreViewmodel_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ai::PreViewmodel>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_PreViewmodel_00024CppProxy_native_1fileDelete(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::PreViewmodel>(nativeRef);
        ref->file_delete();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
