// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "http_result.hpp"

namespace djinni_generated {

class NativeHttpResult final : ::djinni::JniInterface<::ai::HttpResult, NativeHttpResult> {
public:
    using CppType = std::shared_ptr<::ai::HttpResult>;
    using CppOptType = std::shared_ptr<::ai::HttpResult>;
    using JniType = jobject;

    using Boxed = NativeHttpResult;

    ~NativeHttpResult();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeHttpResult>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeHttpResult>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeHttpResult();
    friend ::djinni::JniClass<NativeHttpResult>;
    friend ::djinni::JniInterface<::ai::HttpResult, NativeHttpResult>;

};

}  // namespace djinni_generated
