// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "djinni_support.hpp"
#include "transaction_state.hpp"

namespace djinni_generated {

class NativeTransactionState final : ::djinni::JniEnum {
public:
    using CppType = ::ai::TransactionState;
    using JniType = jobject;

    using Boxed = NativeTransactionState;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeTransactionState>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeTransactionState>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeTransactionState() : JniEnum("net/ai/TransactionState") {}
    friend ::djinni::JniClass<NativeTransactionState>;
};

}  // namespace djinni_generated
