// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include "block.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBlock final {
public:
    using CppType = ::ai::Block;
    using JniType = jobject;

    using Boxed = NativeBlock;

    ~NativeBlock();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeBlock();
    friend ::djinni::JniClass<NativeBlock>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/ai/Block") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(IIII)V") };
    const jfieldID field_mRowBeg { ::djinni::jniGetFieldID(clazz.get(), "mRowBeg", "I") };
    const jfieldID field_mRowEnd { ::djinni::jniGetFieldID(clazz.get(), "mRowEnd", "I") };
    const jfieldID field_mColBeg { ::djinni::jniGetFieldID(clazz.get(), "mColBeg", "I") };
    const jfieldID field_mColEnd { ::djinni::jniGetFieldID(clazz.get(), "mColEnd", "I") };
};

}  // namespace djinni_generated
