// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeVoidResult.hpp"  // my header

namespace djinni_generated {

NativeVoidResult::NativeVoidResult() : ::djinni::JniInterface<::ai::VoidResult, NativeVoidResult>("net/ai/VoidResult$CppProxy") {}

NativeVoidResult::~NativeVoidResult() = default;


CJNIEXPORT void JNICALL Java_net_ai_VoidResult_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ai::VoidResult>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_VoidResult_00024CppProxy_native_1onResult(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::VoidResult>(nativeRef);
        ref->on_result();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
