// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#include "NativeLongResult.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLongResult::NativeLongResult() : ::djinni::JniInterface<::ai::LongResult, NativeLongResult>("net/ai/LongResult$CppProxy") {}

NativeLongResult::~NativeLongResult() = default;


CJNIEXPORT void JNICALL Java_net_ai_LongResult_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ai::LongResult>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_net_ai_LongResult_00024CppProxy_native_1onResult(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_size)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ai::LongResult>(nativeRef);
        ref->on_result(::djinni::I64::toCpp(jniEnv, j_size));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
