// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include <functional>

namespace ai {

enum class Align : int {
    LEFT,
    CENTER,
    RIGHT,
    NONE,
};

}  // namespace ai

namespace std {

template <>
struct hash<::ai::Align> {
    size_t operator()(::ai::Align type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
