// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace ai {

struct Block final {
    int32_t row_beg;
    int32_t row_end;
    int32_t col_beg;
    int32_t col_end;

    Block(int32_t row_beg_,
          int32_t row_end_,
          int32_t col_beg_,
          int32_t col_end_)
    : row_beg(std::move(row_beg_))
    , row_end(std::move(row_end_))
    , col_beg(std::move(col_beg_))
    , col_end(std::move(col_end_))
    {}
};

}  // namespace ai
