// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

namespace ai {

class CancellationToken {
public:
    virtual ~CancellationToken() {}

    virtual void cancel() = 0;
};

}  // namespace ai
