// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include <functional>

namespace ai {

enum class Colour : int {
    WHITE,
    LIGHT_BLUE,
    DIRTY_BLUE,
    DARK_GREY,
    LIGHT_GREY,
    PURPLE,
    RED,
    NONE,
};

}  // namespace ai

namespace std {

template <>
struct hash<::ai::Colour> {
    size_t operator()(::ai::Colour type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
