// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace ai {

enum class LogType;

class Diagnostic {
public:
    virtual ~Diagnostic() {}

    virtual void log(LogType type, int32_t line, const std::string & file, const std::string & message) = 0;

    virtual void log_lines(LogType type, int32_t line, const std::string & file, const std::vector<std::string> & messages) = 0;
};

}  // namespace ai
