// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace ai {

enum class FileState;
struct DirectoriesDetail;
struct FilesDetail;

class DirectoryView {
public:
    virtual ~DirectoryView() {}

    virtual void refresh_list(const std::vector<int32_t> & folder_path, const DirectoriesDetail & dirs, const FilesDetail & files, const std::vector<std::string> & new_directory_names, const std::vector<std::string> & new_file_names) = 0;

    virtual void file_states_changed(const std::vector<int32_t> & folder_path, const std::vector<int32_t> & file_ids, const std::vector<FileState> & states) = 0;

    virtual void file_changed(const std::vector<int32_t> & folder_path, int32_t file_id, int32_t file_name_id, int64_t size, int32_t percentage, FileState state, const std::vector<uint8_t> & thumbnail) = 0;
};

}  // namespace ai
