// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <cstdint>
#include <utility>
#include <vector>

namespace ai {

struct DirectoriesDetail final {
    std::vector<int32_t> ids;
    std::vector<int32_t> titles;

    DirectoriesDetail(std::vector<int32_t> ids_,
                      std::vector<int32_t> titles_)
    : ids(std::move(ids_))
    , titles(std::move(titles_))
    {}
};

}  // namespace ai
