// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#pragma once

#include "element_type.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace ai {

struct Element final {
    int32_t group;
    ElementType type;
    int32_t input_id;
    std::string title;
    std::string value;

    Element(int32_t group_,
            ElementType type_,
            int32_t input_id_,
            std::string title_,
            std::string value_)
    : group(std::move(group_))
    , type(std::move(type_))
    , input_id(std::move(input_id_))
    , title(std::move(title_))
    , value(std::move(value_))
    {}
};

}  // namespace ai
