// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include <functional>

namespace ai {

enum class FieldType : int {
    INPUT,
    LABEL,
    EXPAND,
    BACK,
    ERROR,
    CHAT,
    CONSOLE,
    LINK,
    BUTTON,
    LOGO,
    PANEL_BREAK,
    VERTICAL_SPACE,
    HELP,
};

}  // namespace ai

namespace std {

template <>
struct hash<::ai::FieldType> {
    size_t operator()(::ai::FieldType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
