// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "file_state.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace ai {

struct FileItemDetail final {
    int32_t item_id;
    FileState state;
    bool selected;
    std::string title;
    std::string detail;

    FileItemDetail(int32_t item_id_,
                   FileState state_,
                   bool selected_,
                   std::string title_,
                   std::string detail_)
    : item_id(std::move(item_id_))
    , state(std::move(state_))
    , selected(std::move(selected_))
    , title(std::move(title_))
    , detail(std::move(detail_))
    {}
};

}  // namespace ai
