// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "file_state.hpp"
#include <cstdint>
#include <utility>
#include <vector>

namespace ai {

struct FilesDetail final {
    std::vector<int32_t> ids;
    std::vector<int32_t> titles;
    std::vector<int64_t> sizes;
    std::vector<int32_t> percentages;
    std::vector<FileState> states;
    std::vector<std::vector<uint8_t>> thumbnails;

    FilesDetail(std::vector<int32_t> ids_,
                std::vector<int32_t> titles_,
                std::vector<int64_t> sizes_,
                std::vector<int32_t> percentages_,
                std::vector<FileState> states_,
                std::vector<std::vector<uint8_t>> thumbnails_)
    : ids(std::move(ids_))
    , titles(std::move(titles_))
    , sizes(std::move(sizes_))
    , percentages(std::move(percentages_))
    , states(std::move(states_))
    , thumbnails(std::move(thumbnails_))
    {}
};

}  // namespace ai
