// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace ai {

struct FolderItemDetail final {
    int32_t item_id;
    bool selected;
    std::string title;

    FolderItemDetail(int32_t item_id_,
                     bool selected_,
                     std::string title_)
    : item_id(std::move(item_id_))
    , selected(std::move(selected_))
    , title(std::move(title_))
    {}
};

}  // namespace ai
