// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <memory>
#include <string>

namespace ai {

class FormViewmodel;

class FormView {
public:
    virtual ~FormView() {}

    virtual void replace_form(const std::shared_ptr<FormViewmodel> & vm) = 0;

    virtual void push_form(const std::shared_ptr<FormViewmodel> & vm) = 0;

    virtual void set_screen_name(const std::string & title) = 0;
};

}  // namespace ai
