// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include <cstdint>
#include <string>

namespace ai {

class GenericForm {
public:
    virtual ~GenericForm() {}

    virtual std::string input_get(int32_t input_id) = 0;

    virtual void input_set(int32_t input_id, const std::string & value) = 0;

    virtual void input_configure(int32_t input_id, const std::string & config) = 0;

    virtual bool enable(int32_t element_id, bool enabled) = 0;

    virtual void error(int32_t element_id, const std::string & message) = 0;

    virtual void close() = 0;

    virtual bool validate() = 0;

    virtual void disable_actions() = 0;

    virtual void show_message(const std::string & message) = 0;
};

}  // namespace ai
