// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <string>
#include <utility>

namespace ai {

struct Header final {
    std::string name;
    std::string value;

    Header(std::string name_,
           std::string value_)
    : name(std::move(name_))
    , value(std::move(value_))
    {}
};

}  // namespace ai
