// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <functional>

namespace ai {

enum class HttpVerb : int {
    GET,
    POST,
    PUT,
    PATCH,
    REMOVE,
    OPTIONS,
};

}  // namespace ai

namespace std {

template <>
struct hash<::ai::HttpVerb> {
    size_t operator()(::ai::HttpVerb type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
