// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

namespace ai {

enum class Status;
struct Message;

class OsForm {
public:
    virtual ~OsForm() {}

    virtual void action_result(Status outcome, const std::vector<Message> & lines) = 0;

    virtual void progress(int32_t position, int32_t total) = 0;

    virtual void enable(int32_t group) = 0;

    virtual void disable(int32_t group) = 0;

    virtual std::unordered_map<int32_t, std::string> input() = 0;
};

}  // namespace ai
