// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace ai {

class IntResult;
class OsForm;
class VoidResult;
enum class FileType;
struct Element;

class OsGui {
public:
    virtual ~OsGui() {}

    virtual void show_cloudstore() = 0;

    virtual void gui_thread(const std::shared_ptr<VoidResult> & cb) = 0;

    virtual void back() = 0;

    virtual void open_link_in_browser(const std::string & url) = 0;

    virtual std::shared_ptr<OsForm> create_form(const std::string & title, bool start_hierarchy, int32_t width, int32_t height, const std::shared_ptr<IntResult> & action, const std::vector<Element> & elements) = 0;

    virtual void show_message(const std::string & message) = 0;

    virtual void preview(FileType type, const std::string & path, int32_t file_id, const std::string & file_name) = 0;

    virtual void reset() = 0;
};

}  // namespace ai
