// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

namespace ai {

class PreViewmodel {
public:
    virtual ~PreViewmodel() {}

    virtual void file_delete() = 0;
};

}  // namespace ai
