// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace ai {

struct Progress final {
    int64_t count;
    int64_t total;

    Progress(int64_t count_,
             int64_t total_)
    : count(std::move(count_))
    , total(std::move(total_))
    {}
};

}  // namespace ai
