// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include <string>
#include <utility>
#include <vector>

namespace ai {

struct Reference final {
    std::string name;
    std::vector<std::string> items;

    Reference(std::string name_,
              std::vector<std::string> items_)
    : name(std::move(name_))
    , items(std::move(items_))
    {}
};

}  // namespace ai
