// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace ai {

class Diagnostic;
class OsIo;
class UiCallback;
class View;
class Worker;
enum class ScreenType;

class RootViewmodel {
public:
    virtual ~RootViewmodel() {}

    static std::shared_ptr<RootViewmodel> create(const std::shared_ptr<Worker> & scheduler, const std::string & app_data_location, int32_t thumb_px, const std::shared_ptr<OsIo> & io, const std::shared_ptr<View> & view, ScreenType type, const std::shared_ptr<UiCallback> & callback, const std::shared_ptr<Diagnostic> & logger);
};

}  // namespace ai
