// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <functional>

namespace ai {

enum class ScreenType : int {
    DESKTOP,
    PHONE,
    TABLET,
};

}  // namespace ai

namespace std {

template <>
struct hash<::ai::ScreenType> {
    size_t operator()(::ai::ScreenType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
