// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include <functional>

namespace ai {

enum class Size : int {
    SMALL,
    MEDIUM,
    LARGE,
    NONE,
};

}  // namespace ai

namespace std {

template <>
struct hash<::ai::Size> {
    size_t operator()(::ai::Size type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
