// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "file_state.hpp"
#include <cstdint>
#include <utility>

namespace ai {

struct StateChange final {
    int32_t index;
    FileState state;

    StateChange(int32_t index_,
                FileState state_)
    : index(std::move(index_))
    , state(std::move(state_))
    {}
};

}  // namespace ai
