// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <string>
#include <unordered_map>
#include <vector>

namespace ai {

struct Product;
struct TransactionDetail;

class StoreViewmodel {
public:
    virtual ~StoreViewmodel() {}

    virtual void on_transaction_states(const std::unordered_map<std::string, TransactionDetail> & states) = 0;

    virtual void on_products(const std::vector<Product> & products) = 0;

    virtual void on_restore_fail(const std::string & error_message) = 0;

    virtual void on_restore_finished() = 0;
};

}  // namespace ai
