// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include "align.hpp"
#include "colour.hpp"
#include "size.hpp"
#include "weight.hpp"
#include <cstdint>
#include <utility>

namespace ai {

struct Style final {
    Size size;
    Align align;
    Colour colour;
    Weight weight;
    int32_t width;

    Style(Size size_,
          Align align_,
          Colour colour_,
          Weight weight_,
          int32_t width_)
    : size(std::move(size_))
    , align(std::move(align_))
    , colour(std::move(colour_))
    , weight(std::move(weight_))
    , width(std::move(width_))
    {}
};

}  // namespace ai
