// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

namespace ai {

class Task {
public:
    virtual ~Task() {}

    virtual void run() = 0;
};

}  // namespace ai
