// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <functional>

namespace ai {

enum class TransactionState : int {
    ERROR,
    BUSY,
    PURCHASED,
    RESTORED,
    VERIFY_BLOMP,
};

}  // namespace ai

namespace std {

template <>
struct hash<::ai::TransactionState> {
    size_t operator()(::ai::TransactionState type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
