// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include "transaction_state.hpp"
#include <string>
#include <utility>

namespace ai {

struct TransactionDetail final {
    TransactionState state;
    std::string error_message;

    TransactionDetail(TransactionState state_,
                      std::string error_message_)
    : state(std::move(state_))
    , error_message(std::move(error_message_))
    {}
};

}  // namespace ai
