// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <memory>

namespace ai {

class VoidResult;

class UiCallback {
public:
    virtual ~UiCallback() {}

    virtual void gui_thread(const std::shared_ptr<VoidResult> & cb) = 0;
};

}  // namespace ai
