// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace ai {

class FolderViewmodel;
class FormViewmodel;
class StoreViewmodel;

class View {
public:
    virtual ~View() {}

    virtual void create_main_menu(const std::shared_ptr<FormViewmodel> & root_form_vm, const std::shared_ptr<FolderViewmodel> & root_folder_vm, const std::shared_ptr<FormViewmodel> & user_vm, const std::shared_ptr<FormViewmodel> & plan_vm, const std::shared_ptr<FormViewmodel> & settings_vm) = 0;

    virtual void select_menu(int32_t index) = 0;

    virtual void show_menu(bool visible) = 0;

    virtual void send_invite() = 0;

    virtual void push_form(const std::shared_ptr<FormViewmodel> & vm) = 0;

    virtual void replace_form(const std::shared_ptr<FormViewmodel> & vm) = 0;

    virtual void copy_to_clipboard(const std::string & content) = 0;

    virtual void open_link_in_browser(const std::string & url) = 0;

    virtual void register_store_vm(const std::shared_ptr<StoreViewmodel> & vm) = 0;

    virtual bool is_authorized_for_payments() = 0;

    virtual void fetch_products(const std::vector<std::string> & product_ids) = 0;

    virtual void subscription_purchase(const std::string & email, const std::string & product_id) = 0;

    virtual void subscription_restore(const std::string & email) = 0;

    virtual void subscription_cancel(const std::string & product_id) = 0;

    virtual std::string subscription_receipt(const std::string & product_id) = 0;

    virtual void subscription_manage() = 0;
};

}  // namespace ai
