// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

#pragma once

#include <functional>

namespace ai {

enum class Weight : int {
    NORMAL,
    BOLD,
};

}  // namespace ai

namespace std {

template <>
struct hash<::ai::Weight> {
    size_t operator()(::ai::Weight type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
