// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

#pragma once

#include <memory>

namespace ai {

class Task;

class Worker {
public:
    virtual ~Worker() {}

    virtual void schedule(const std::shared_ptr<Task> & todo) = 0;
};

}  // namespace ai
