// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

package net.ai;

public final class Block {


    /*package*/ final int mRowBeg;

    /*package*/ final int mRowEnd;

    /*package*/ final int mColBeg;

    /*package*/ final int mColEnd;

    public Block(
            int rowBeg,
            int rowEnd,
            int colBeg,
            int colEnd) {
        this.mRowBeg = rowBeg;
        this.mRowEnd = rowEnd;
        this.mColBeg = colBeg;
        this.mColEnd = colEnd;
    }

    public int getRowBeg() {
        return mRowBeg;
    }

    public int getRowEnd() {
        return mRowEnd;
    }

    public int getColBeg() {
        return mColBeg;
    }

    public int getColEnd() {
        return mColEnd;
    }

    @Override
    public String toString() {
        return "Block{" +
                "mRowBeg=" + mRowBeg +
                "," + "mRowEnd=" + mRowEnd +
                "," + "mColBeg=" + mColBeg +
                "," + "mColEnd=" + mColEnd +
        "}";
    }

}
