// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

package net.ai;

public enum Colour {
    WHITE,
    LIGHT_BLUE,
    DIRTY_BLUE,
    DARK_GREY,
    LIGHT_GREY,
    PURPLE,
    RED,
    NONE,
    ;
}
