// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

package net.ai;

public enum DataType {
    TEXT,
    MULTILINE_TEXT,
    BOOLEAN,
    EMAIL,
    PASSWORD,
    REFERENCE,
    CHOICE,
    SKYPE,
    PHONE,
    CURRENCY,
    URL,
    INTEGER,
    RATING,
    ;
}
