// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

import java.util.ArrayList;

public abstract class Diagnostic {
    public abstract void log(LogType type, int line, String file, String message);

    public abstract void logLines(LogType type, int line, String file, ArrayList<String> messages);
}
