// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

import java.util.ArrayList;

public abstract class DirectoryView {
    public abstract void refreshList(ArrayList<Integer> folderPath, DirectoriesDetail dirs, FilesDetail files, ArrayList<String> newDirectoryNames, ArrayList<String> newFileNames);

    public abstract void fileStatesChanged(ArrayList<Integer> folderPath, ArrayList<Integer> fileIds, ArrayList<FileState> states);

    public abstract void fileChanged(ArrayList<Integer> folderPath, int fileId, int fileNameId, long size, int percentage, FileState state, byte[] thumbnail);
}
