// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

package net.ai;

public final class Element {


    /*package*/ final int mGroup;

    /*package*/ final ElementType mType;

    /*package*/ final int mInputId;

    /*package*/ final String mTitle;

    /*package*/ final String mValue;

    public Element(
            int group,
            ElementType type,
            int inputId,
            String title,
            String value) {
        this.mGroup = group;
        this.mType = type;
        this.mInputId = inputId;
        this.mTitle = title;
        this.mValue = value;
    }

    public int getGroup() {
        return mGroup;
    }

    public ElementType getType() {
        return mType;
    }

    public int getInputId() {
        return mInputId;
    }

    public String getTitle() {
        return mTitle;
    }

    public String getValue() {
        return mValue;
    }

    @Override
    public String toString() {
        return "Element{" +
                "mGroup=" + mGroup +
                "," + "mType=" + mType +
                "," + "mInputId=" + mInputId +
                "," + "mTitle=" + mTitle +
                "," + "mValue=" + mValue +
        "}";
    }

}
