// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

package net.ai;

public enum ElementType {
    BUTTON,
    TEXT_INPUT,
    BOOL_INPUT,
    EMAIL_INPUT,
    LABEL,
    PASSWORD_INPUT,
    TEXT,
    ;
}
