// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

package net.ai;

public enum FieldType {
    INPUT,
    LABEL,
    EXPAND,
    BACK,
    ERROR,
    CHAT,
    CONSOLE,
    LINK,
    BUTTON,
    LOGO,
    PANEL_BREAK,
    VERTICAL_SPACE,
    HELP,
    ;
}
