// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public final class FileItemDetail {


    /*package*/ final int mItemId;

    /*package*/ final FileState mState;

    /*package*/ final boolean mSelected;

    /*package*/ final String mTitle;

    /*package*/ final String mDetail;

    public FileItemDetail(
            int itemId,
            FileState state,
            boolean selected,
            String title,
            String detail) {
        this.mItemId = itemId;
        this.mState = state;
        this.mSelected = selected;
        this.mTitle = title;
        this.mDetail = detail;
    }

    public int getItemId() {
        return mItemId;
    }

    public FileState getState() {
        return mState;
    }

    public boolean getSelected() {
        return mSelected;
    }

    public String getTitle() {
        return mTitle;
    }

    public String getDetail() {
        return mDetail;
    }

    @Override
    public String toString() {
        return "FileItemDetail{" +
                "mItemId=" + mItemId +
                "," + "mState=" + mState +
                "," + "mSelected=" + mSelected +
                "," + "mTitle=" + mTitle +
                "," + "mDetail=" + mDetail +
        "}";
    }

}
