// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

import java.util.ArrayList;

public final class FilesDetail {


    /*package*/ final ArrayList<Integer> mIds;

    /*package*/ final ArrayList<Integer> mTitles;

    /*package*/ final ArrayList<Long> mSizes;

    /*package*/ final ArrayList<Integer> mPercentages;

    /*package*/ final ArrayList<FileState> mStates;

    /*package*/ final ArrayList<byte[]> mThumbnails;

    public FilesDetail(
            ArrayList<Integer> ids,
            ArrayList<Integer> titles,
            ArrayList<Long> sizes,
            ArrayList<Integer> percentages,
            ArrayList<FileState> states,
            ArrayList<byte[]> thumbnails) {
        this.mIds = ids;
        this.mTitles = titles;
        this.mSizes = sizes;
        this.mPercentages = percentages;
        this.mStates = states;
        this.mThumbnails = thumbnails;
    }

    public ArrayList<Integer> getIds() {
        return mIds;
    }

    public ArrayList<Integer> getTitles() {
        return mTitles;
    }

    public ArrayList<Long> getSizes() {
        return mSizes;
    }

    public ArrayList<Integer> getPercentages() {
        return mPercentages;
    }

    public ArrayList<FileState> getStates() {
        return mStates;
    }

    public ArrayList<byte[]> getThumbnails() {
        return mThumbnails;
    }

    @Override
    public String toString() {
        return "FilesDetail{" +
                "mIds=" + mIds +
                "," + "mTitles=" + mTitles +
                "," + "mSizes=" + mSizes +
                "," + "mPercentages=" + mPercentages +
                "," + "mStates=" + mStates +
                "," + "mThumbnails=" + mThumbnails +
        "}";
    }

}
