// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public enum FileState {
    NORMAL,
    DOWNLOADING,
    UPLOADING,
    FAILED,
    LOCAL,
    DELETING,
    DELETED,
    ;
}
