// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public abstract class FormView {
    public abstract void replaceForm(FormViewmodel vm);

    public abstract void pushForm(FormViewmodel vm);

    public abstract void setScreenName(String title);
}
