// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

package net.ai;

public abstract class GenericForm {
    public abstract String inputGet(int inputId);

    public abstract void inputSet(int inputId, String value);

    public abstract void inputConfigure(int inputId, String config);

    public abstract boolean enable(int elementId, boolean enabled);

    public abstract void error(int elementId, String message);

    public abstract void close();

    public abstract boolean validate();

    public abstract void disableActions();

    public abstract void showMessage(String message);
}
