// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public final class Header {


    /*package*/ final String mName;

    /*package*/ final String mValue;

    public Header(
            String name,
            String value) {
        this.mName = name;
        this.mValue = value;
    }

    public String getName() {
        return mName;
    }

    public String getValue() {
        return mValue;
    }

    @Override
    public String toString() {
        return "Header{" +
                "mName=" + mName +
                "," + "mValue=" + mValue +
        "}";
    }

}
