// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public enum HttpVerb {
    GET,
    POST,
    PUT,
    PATCH,
    REMOVE,
    OPTIONS,
    ;
}
