// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class HttpResult {
    public abstract void onResult(int statusCode, ArrayList<Header> headers, String data);

    private static final class CppProxy extends HttpResult
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public void onResult(int statusCode, ArrayList<Header> headers, String data)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_onResult(this.nativeRef, statusCode, headers, data);
        }
        private native void native_onResult(long _nativeRef, int statusCode, ArrayList<Header> headers, String data);
    }
}
