// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public final class Message {


    /*package*/ final int mField;

    /*package*/ final String mContent;

    public Message(
            int field,
            String content) {
        this.mField = field;
        this.mContent = content;
    }

    public int getField() {
        return mField;
    }

    public String getContent() {
        return mContent;
    }

    @Override
    public String toString() {
        return "Message{" +
                "mField=" + mField +
                "," + "mContent=" + mContent +
        "}";
    }

}
