// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form.djinni

package net.ai;

import java.util.ArrayList;
import java.util.HashMap;

public abstract class OsForm {
    public abstract void actionResult(Status outcome, ArrayList<Message> lines);

    public abstract void progress(int position, int total);

    public abstract void enable(int group);

    public abstract void disable(int group);

    public abstract HashMap<Integer, String> input();
}
