// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

import java.util.ArrayList;

public abstract class OsGui {
    public abstract void showCloudstore();

    public abstract void guiThread(VoidResult cb);

    public abstract void back();

    public abstract void openLinkInBrowser(String url);

    public abstract OsForm createForm(String title, boolean startHierarchy, int width, int height, IntResult action, ArrayList<Element> elements);

    public abstract void showMessage(String message);

    public abstract void preview(FileType type, String path, int fileId, String fileName);

    public abstract void reset();
}
