// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

import java.util.ArrayList;

public abstract class OsIo {
    public abstract void log(LogType type, int line, String file, String message);

    public abstract void logLines(LogType type, int line, String file, ArrayList<String> messages);

    public abstract void fileReadall(String path, BinaryResult result);

    public abstract void fileWriteall(String path, byte[] content, BoolResult result);

    public abstract void fileWriteallSafely(String path, byte[] content, BoolResult result);

    public abstract void fileWritePassword(String username, String password, BoolResult result);

    public abstract void fileReadPassword(String username, StringResult result);

    public abstract void fileSize(String path, LongResult result);

    public abstract boolean fileThumbnail(String path, FileType type, BinaryResult result);

    public abstract void copyFile(String currentPath, String newPath, BoolResult result);

    public abstract void makePath(String path, BoolResult result);

    public abstract void renameFile(String currentPath, String newPath, BoolResult result);

    public abstract CancellationToken httpRequest(HttpVerb verb, String url, ArrayList<Header> headers, String body, HttpResult result);

    public abstract CancellationToken httpUploadFile(HttpVerb verb, String url, String filePath, ArrayList<Header> headers, HttpProgressResult result);

    public abstract CancellationToken httpDownloadFile(String url, String filePath, ArrayList<Header> headers, long size, String md5, HttpProgressResult result);

    public abstract void wait(int millis, VoidResult result);

    public abstract void fileExpandDirectories(ArrayList<String> paths, StringsResult result);

    public abstract void fileCopyHierarchy(String destRootPath, ArrayList<String> destRelativePaths, ArrayList<String> srcPaths);

    public abstract void fileClearCache(String username, BoolResult result);
}
