// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public final class Product {


    /*package*/ final String mProductId;

    /*package*/ final String mTitle;

    /*package*/ final String mProductDescription;

    /*package*/ final float mPrice;

    /*package*/ final String mFormattedPrice;

    public Product(
            String productId,
            String title,
            String productDescription,
            float price,
            String formattedPrice) {
        this.mProductId = productId;
        this.mTitle = title;
        this.mProductDescription = productDescription;
        this.mPrice = price;
        this.mFormattedPrice = formattedPrice;
    }

    public String getProductId() {
        return mProductId;
    }

    public String getTitle() {
        return mTitle;
    }

    public String getProductDescription() {
        return mProductDescription;
    }

    public float getPrice() {
        return mPrice;
    }

    public String getFormattedPrice() {
        return mFormattedPrice;
    }

    @Override
    public String toString() {
        return "Product{" +
                "mProductId=" + mProductId +
                "," + "mTitle=" + mTitle +
                "," + "mProductDescription=" + mProductDescription +
                "," + "mPrice=" + mPrice +
                "," + "mFormattedPrice=" + mFormattedPrice +
        "}";
    }

}
