// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public final class Progress {


    /*package*/ final long mCount;

    /*package*/ final long mTotal;

    public Progress(
            long count,
            long total) {
        this.mCount = count;
        this.mTotal = total;
    }

    public long getCount() {
        return mCount;
    }

    public long getTotal() {
        return mTotal;
    }

    @Override
    public String toString() {
        return "Progress{" +
                "mCount=" + mCount +
                "," + "mTotal=" + mTotal +
        "}";
    }

}
