// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

package net.ai;

import java.util.ArrayList;

public final class Reference {


    /*package*/ final String mName;

    /*package*/ final ArrayList<String> mItems;

    public Reference(
            String name,
            ArrayList<String> items) {
        this.mName = name;
        this.mItems = items;
    }

    public String getName() {
        return mName;
    }

    public ArrayList<String> getItems() {
        return mItems;
    }

    @Override
    public String toString() {
        return "Reference{" +
                "mName=" + mName +
                "," + "mItems=" + mItems +
        "}";
    }

}
