// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from form2.djinni

package net.ai;

public final class Style {


    /*package*/ final Size mSize;

    /*package*/ final Align mAlign;

    /*package*/ final Colour mColour;

    /*package*/ final Weight mWeight;

    /*package*/ final int mWidth;

    public Style(
            Size size,
            Align align,
            Colour colour,
            Weight weight,
            int width) {
        this.mSize = size;
        this.mAlign = align;
        this.mColour = colour;
        this.mWeight = weight;
        this.mWidth = width;
    }

    public Size getSize() {
        return mSize;
    }

    public Align getAlign() {
        return mAlign;
    }

    public Colour getColour() {
        return mColour;
    }

    public Weight getWeight() {
        return mWeight;
    }

    public int getWidth() {
        return mWidth;
    }

    @Override
    public String toString() {
        return "Style{" +
                "mSize=" + mSize +
                "," + "mAlign=" + mAlign +
                "," + "mColour=" + mColour +
                "," + "mWeight=" + mWeight +
                "," + "mWidth=" + mWidth +
        "}";
    }

}
