// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public final class TransactionDetail {


    /*package*/ final TransactionState mState;

    /*package*/ final String mErrorMessage;

    public TransactionDetail(
            TransactionState state,
            String errorMessage) {
        this.mState = state;
        this.mErrorMessage = errorMessage;
    }

    public TransactionState getState() {
        return mState;
    }

    public String getErrorMessage() {
        return mErrorMessage;
    }

    @Override
    public String toString() {
        return "TransactionDetail{" +
                "mState=" + mState +
                "," + "mErrorMessage=" + mErrorMessage +
        "}";
    }

}
