// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

public enum TransactionState {
    ERROR,
    BUSY,
    PURCHASED,
    RESTORED,
    VERIFY_BLOMP,
    ;
}
