// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portal.djinni

package net.ai;

import java.util.ArrayList;

public abstract class View {
    public abstract void createMainMenu(FormViewmodel rootFormVm, FolderViewmodel rootFolderVm, FormViewmodel userVm, FormViewmodel planVm, FormViewmodel settingsVm);

    public abstract void selectMenu(int index);

    public abstract void showMenu(boolean visible);

    public abstract void sendInvite();

    public abstract void pushForm(FormViewmodel vm);

    public abstract void replaceForm(FormViewmodel vm);

    public abstract void copyToClipboard(String content);

    public abstract void openLinkInBrowser(String url);

    public abstract void registerStoreVm(StoreViewmodel vm);

    public abstract boolean isAuthorizedForPayments();

    public abstract void fetchProducts(ArrayList<String> productIds);

    public abstract void subscriptionPurchase(String email, String productId);

    public abstract void subscriptionRestore(String email);

    public abstract void subscriptionCancel(String productId);

    public abstract String subscriptionReceipt(String productId);

    public abstract void subscriptionManage();
}
